use serde_json::Value;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn escaped_path(path: &Path) -> String {
    path.to_string_lossy()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("rkaf-validate lives under crates/");
    let schema_dir = repo_root.join("compiled/json-schema/core");
    println!("cargo:rerun-if-changed={}", schema_dir.display());

    let mut entries: BTreeMap<String, (String, PathBuf)> = BTreeMap::new();
    let mut schema_paths: Vec<PathBuf> = fs::read_dir(&schema_dir)
        .expect("read compiled JSON Schema directory")
        .map(|entry| entry.expect("read schema directory entry").path())
        .filter(|path| {
            path.file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.ends_with(".schema.json"))
        })
        .collect();
    schema_paths.sort();

    for path in schema_paths {
        println!("cargo:rerun-if-changed={}", path.display());
        let raw = fs::read_to_string(&path).expect("read compiled schema");
        let parsed: Value = serde_json::from_str(&raw).expect("parse compiled schema");
        let Some(defs) = parsed.get("$defs").and_then(Value::as_object) else {
            continue;
        };
        for (class_name, class_schema) in defs {
            let type_iri = class_schema
                .get("properties")
                .and_then(|props| props.get("@type"))
                .and_then(|type_schema| type_schema.get("const"))
                .and_then(Value::as_str);
            let Some(type_iri) = type_iri else {
                continue;
            };
            if !type_iri.starts_with("rkaf:") {
                continue;
            }
            entries
                .entry(type_iri.to_string())
                .or_insert_with(|| (class_name.to_string(), path.clone()));
        }
    }

    let mut output = String::from(
        "// @generated by crates/rkaf-validate/build.rs\n\
         pub(crate) const EMBEDDED_SCHEMAS: &[(&str, &str, &str)] = &[\n",
    );
    for (type_iri, (class_name, path)) in entries {
        output.push_str(&format!(
            "    (\"{type_iri}\", \"{class_name}\", include_str!(\"{}\")),\n",
            escaped_path(&path)
        ));
    }
    output.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("schema_registry.rs"), output).expect("write schema registry");
}
