"""The deterministic layer of the Rulespec (RKAF) document projection."""

from .attestations import ATTESTOR_KIND_AI_MODEL, DECISION_ENDORSED_FOR_REVIEW, AttestationError, attestation_row
from .evidence import EvidenceOffsetResolution, resolve_exact_evidence_offsets
from .projection import (
    ASSERTION_ORIGIN_DETERMINISTIC,
    ASSERTION_ORIGIN_MODEL,
    ASSIGNMENT_ROLE_ABSOLUTE_IRIS,
    ASSIGNMENT_ROLE_IRIS,
    DETERMINISTIC_USAGE_ELIGIBILITY,
    DOCUMENT_DOCKET_PREDICATE,
    EMIT_DOCUMENT_DOCKET_EDGE,
    EMIT_PROFILE_EDGE_PROJECTIONS,
    FRAGMENT_URN_PATTERN,
    MODEL_ATTESTATION_DECISION,
    MODEL_USAGE_ELIGIBILITY,
    PROJECTION_SCHEMA_VERSION,
    SOURCE_EXACT_EVIDENCE_GRADE,
    ConceptJudgment,
    DeterministicEdge,
    ExtractionActivitySpec,
    InMemoryTables,
    ModelLayer,
    OffsetVerificationError,
    ProfileFacts,
    ProjectedFragment,
    ProjectionError,
    ProjectionResult,
    ProjectionSettings,
    PublishedTables,
    SourceArtifact,
    VocabularyConcept,
    assemble,
    encode_for_uri,
    federal_register_facts,
    fragment_urn,
    ground_literal,
    request_contract_digest,
    unified_agenda_facts,
    verify_candidate_rows,
    verify_fragment,
)
from .provenance import RunContext, canonical_json, stable_id, text_digest

__version__ = "0.1.1"

__all__ = [
    "ASSERTION_ORIGIN_DETERMINISTIC",
    "ASSERTION_ORIGIN_MODEL",
    "ASSIGNMENT_ROLE_ABSOLUTE_IRIS",
    "ASSIGNMENT_ROLE_IRIS",
    "ATTESTOR_KIND_AI_MODEL",
    "DECISION_ENDORSED_FOR_REVIEW",
    "DETERMINISTIC_USAGE_ELIGIBILITY",
    "DOCUMENT_DOCKET_PREDICATE",
    "EMIT_DOCUMENT_DOCKET_EDGE",
    "EMIT_PROFILE_EDGE_PROJECTIONS",
    "FRAGMENT_URN_PATTERN",
    "MODEL_ATTESTATION_DECISION",
    "MODEL_USAGE_ELIGIBILITY",
    "PROJECTION_SCHEMA_VERSION",
    "SOURCE_EXACT_EVIDENCE_GRADE",
    "AttestationError",
    "ConceptJudgment",
    "DeterministicEdge",
    "EvidenceOffsetResolution",
    "ExtractionActivitySpec",
    "InMemoryTables",
    "ModelLayer",
    "OffsetVerificationError",
    "ProfileFacts",
    "ProjectedFragment",
    "ProjectionError",
    "ProjectionResult",
    "ProjectionSettings",
    "PublishedTables",
    "RunContext",
    "SourceArtifact",
    "VocabularyConcept",
    "assemble",
    "attestation_row",
    "canonical_json",
    "encode_for_uri",
    "federal_register_facts",
    "fragment_urn",
    "ground_literal",
    "request_contract_digest",
    "resolve_exact_evidence_offsets",
    "stable_id",
    "text_digest",
    "unified_agenda_facts",
    "verify_candidate_rows",
    "verify_fragment",
]
