"""The Rulespec contract, importable: schemas, shapes, context, enums, terms.

A consumer of Rulespec needs four things that used to require a checkout: the
compiled JSON Schemas, the SHACL (compiled and hand-authored), the JSON-LD
context, and the closed vocabulary — the lattices, the enums, and the term
names themselves. `rulespec_conformance.conformance_lib` already reads the
first three for the packaged validator's own use; this package is the same
data with a consumer-facing surface, plus the vocabulary as Python constants:

    from rulespec_conformance.contract import USAGE_ELIGIBILITY, resources, terms

    USAGE_ELIGIBILITY.index(level)          # rank in the normative lattice
    resources.json_schema("artifact")       # compiled Draft 2020-12 schema
    resources.shacl("warrant")              # compiled Turtle
    resources.shapes("rkaf-shapes-core")    # hand-authored Turtle
    resources.context()                     # the JSON-LD context document
    terms.hasContentDigest                  # "rkaf:hasContentDigest"

It lives inside `rulespec-conformance` rather than in a distribution of its
own because it is the same bytes: the wheel already force-includes
`compiled/`, `shapes/` and the context, and a second distribution would either
ship a second copy of them or depend on this one to find them. The name says
conformance; the contents are what conforming to Rulespec requires.

`enums` and `terms` are generated by `tools/build_contract_exports.py` from
the CUE and the normative specs, and `make test-audits` fails on any drift.
Nothing here is hand-maintained except `resources` and the `Term` type.
"""

from __future__ import annotations

from . import enums as enums
from . import resources as resources
from . import terms as terms
from ._term import RKAF_NAMESPACE as RKAF_NAMESPACE
from ._term import Term as Term
from .enums import *  # noqa: F403  (generated module; `enums.__all__` is closed)

#: The Rulespec version this contract was cut from, e.g. `0.2.0-pre.10`.
VERSION: str = resources.version()

__all__ = [
    "RKAF_NAMESPACE",
    "Term",
    "VERSION",
    "enums",
    "resources",
    "terms",
    *enums.__all__,
]
