# GENERATED by tools/build_contract_exports.py — do not edit.
#
# Source: constraints/**/*.cue, read through tools/constraints_compile.py.
"""Every closed enum and lattice the Rulespec CUE declares.

Each constant is the enum's members as a tuple in CUE DECLARATION ORDER,
which is the order the compiled JSON Schema `enum` arrays carry and the
order `#UsageEligibility` calls normative: usage eligibility ascends from
`rkaf:notEligible` to `rkaf:officialUse`, consumers MAY narrow and MUST NOT
broaden, and every floor/ceiling comparison downstream is a rank against
this tuple. Where a CUE comment does not call order normative, membership is
the contract and the order is simply the source's.

Values are the literal wire strings, prefix and all — most are `rkaf:`, but
`#SelectorKind` carries `oa:`, `#SkosMappingPredicate` carries `skos:`, and
`#ValueDatatype` carries `xsd:`.
"""

from __future__ import annotations

#: `#AccessScopeKind` — constraints/core/access-scope.cue
ACCESS_SCOPE_KIND: tuple[str, ...] = (
    "rkaf:public",
    "rkaf:partnerVisible",
    "rkaf:organizationVisible",
    "rkaf:roleRestricted",
    "rkaf:personalRestricted",
    "rkaf:regulatoryRestricted",
    "rkaf:embargoUntil",
)

#: `#AgendaItemIdentifierScheme` — constraints/profiles/us-rulemaking/rulemaking.cue
AGENDA_ITEM_IDENTIFIER_SCHEME: tuple[str, ...] = (
    "rkaf:us-rin",
)

#: `#AgendaObservationIdentifierScheme` — constraints/profiles/us-rulemaking/rulemaking.cue
AGENDA_OBSERVATION_IDENTIFIER_SCHEME: tuple[str, ...] = (
    "rkaf:urn-persistent",
)

#: `#AgendaPriority` — constraints/profiles/us-rulemaking/rulemaking.cue
AGENDA_PRIORITY: tuple[str, ...] = (
    "rkaf:agendaPriorityEconomicallySignificant",
    "rkaf:agendaPriorityOtherSignificant",
    "rkaf:agendaPrioritySubstantiveNonsignificant",
    "rkaf:agendaPriorityRoutineFrequent",
    "rkaf:agendaPriorityInfoAdminOther",
)

#: `#AgendaScopeStatus` — constraints/profiles/us-rulemaking/rulemaking.cue
AGENDA_SCOPE_STATUS: tuple[str, ...] = (
    "rkaf:agendaScopeRecurring",
    "rkaf:agendaScopeSingleObserved",
    "rkaf:agendaScopeUnresolved",
)

#: `#AgendaStage` — constraints/profiles/us-rulemaking/rulemaking.cue
AGENDA_STAGE: tuple[str, ...] = (
    "rkaf:agendaPrerule",
    "rkaf:agendaProposed",
    "rkaf:agendaFinal",
    "rkaf:agendaLongterm",
    "rkaf:agendaCompleted",
)

#: `#ArtifactIdentifierScheme` — constraints/core/artifact.cue
ARTIFACT_IDENTIFIER_SCHEME: tuple[str, ...] = (
    "rkaf:eli",
    "rkaf:eli-dl",
    "rkaf:eli-i",
    "rkaf:uslm",
    "rkaf:aknt-eId",
    "rkaf:doi",
    "rkaf:isbn",
    "rkaf:issn",
    "rkaf:cid",
    "rkaf:hash-sha256",
    "rkaf:urn-persistent",
    "rkaf:formspec-need",
    "rkaf:partner-defined",
)

#: `#AssertionOrigin` — constraints/core/assertion.cue
ASSERTION_ORIGIN: tuple[str, ...] = (
    "rkaf:humanAsserted",
    "rkaf:aiSuggested",
    "rkaf:imported",
    "rkaf:deterministicExtraction",
)

#: `#AssertionPolarity` — constraints/core/assertion.cue
ASSERTION_POLARITY: tuple[str, ...] = (
    "rkaf:affirmed",
    "rkaf:denied",
)

#: `#AttestationDecision` — constraints/core/attestation.cue
ATTESTATION_DECISION: tuple[str, ...] = (
    "rkaf:approved",
    "rkaf:approvedWithConditions",
    "rkaf:rejected",
    "rkaf:abstained",
    "rkaf:advisory",
    "rkaf:endorsedForReview",
    "rkaf:flaggedForReview",
)

#: `#AttestorKind` — constraints/core/attestation.cue
ATTESTOR_KIND: tuple[str, ...] = (
    "rkaf:humanUser",
    "rkaf:aiModel",
    "rkaf:aiAgent",
    "rkaf:automatedParser",
    "rkaf:team",
    "rkaf:organization",
    "rkaf:community",
    "rkaf:formalReviewer",
    "rkaf:conceptMintingAuthority",
)

#: `#AuthorityChainStatus` — constraints/core/bridge-validation-result.cue
AUTHORITY_CHAIN_STATUS: tuple[str, ...] = (
    "rkaf:valid",
    "rkaf:broken",
    "rkaf:staleForCurrentUse",
    "rkaf:validForPointInTimeOnly",
    "rkaf:brokenForNewCases",
    "rkaf:missingAuthority",
    "rkaf:unsupportedAuthorityKind",
)

#: `#AuthorityKind` — constraints/core/authority.cue
AUTHORITY_KIND: tuple[str, ...] = (
    "rkaf:legal",
    "rkaf:statutory",
    "rkaf:regulatory",
    "rkaf:delegated",
    "rkaf:organizational",
    "rkaf:contractual",
    "rkaf:localOperational",
    "rkaf:publication",
)

#: `#BridgeIssueKind` — constraints/core/bridge-issue-attestation-contract.cue
BRIDGE_ISSUE_KIND: tuple[str, ...] = (
    "rkaf:staleDep",
    "rkaf:unresolvedConcept",
    "rkaf:brokenAuthority",
    "rkaf:unsupportedAnchor",
)

#: `#BridgeResult` — constraints/core/bridge-validation-result.cue
BRIDGE_RESULT: tuple[str, ...] = (
    "rkaf:accepted",
    "rkaf:acceptedWithWarnings",
    "rkaf:rejected",
)

#: `#CalibrationStatus` — constraints/core/confidence-record.cue
CALIBRATION_STATUS: tuple[str, ...] = (
    "rkaf:uncalibrated",
    "rkaf:calibratedAgainst",
    "rkaf:humanEstimated",
    "rkaf:consensus",
)

#: `#ClaimantAttribution` — constraints/core/source-claimant.cue
CLAIMANT_ATTRIBUTION: tuple[str, ...] = (
    "rkaf:claimantNamedInSource",
    "rkaf:claimantImpliedBySource",
    "rkaf:claimantIsDocumentIssuer",
    "rkaf:claimantNotStated",
)

#: `#ClosureClaimStatus` — constraints/analysis/closure-claim.cue
CLOSURE_CLAIM_STATUS: tuple[str, ...] = (
    "rkaf:closureClaimDisabled",
)

#: `#ComposedLifecycleEventKind` — constraints/profiles/us-rulemaking/us-lifecycle-event.cue
COMPOSED_LIFECYCLE_EVENT_KIND: tuple[str, ...] = (
    "rkaf:revalidation",
    "rkaf:revalidationClosure",
    "rkaf:amendment",
    "rkaf:supersession",
    "rkaf:rescission",
    "rkaf:materialRevision",
    "rkaf:editorialRevision",
    "rkaf:conceptLifecycle",
    "rkaf:proceedingPrerule",
    "rkaf:proceedingProposed",
    "rkaf:proceedingSupplemental",
    "rkaf:proceedingFinal",
    "rkaf:proceedingWithdrawn",
    "rkaf:proceedingLongterm",
    "rkaf:proceedingConcluded",
    "rkaf:proceedingVacated",
    "rkaf:proceedingStayed",
    "rkaf:proceedingRemanded",
    "rkaf:proceedingReinstated",
    "rkaf:proceedingDisapproved",
)

#: `#ConceptAssignmentPredicate` — constraints/core/concept-assignment.cue
CONCEPT_ASSIGNMENT_PREDICATE: tuple[str, ...] = (
    "rkaf:assignmentPrimary",
    "rkaf:assignmentSubstantive",
    "rkaf:assignmentMention",
    "rkaf:assignmentContextual",
)

#: `#ConceptLifecycleOperation` — constraints/core/lifecycle-event.cue
CONCEPT_LIFECYCLE_OPERATION: tuple[str, ...] = (
    "rkaf:deprecation",
    "rkaf:withdrawal",
    "rkaf:replacement",
    "rkaf:split",
    "rkaf:merge",
    "rkaf:promotion",
    "rkaf:demotion",
)

#: `#ConceptResolutionCacheStatus` — constraints/core/concept-resolution-result.cue
CONCEPT_RESOLUTION_CACHE_STATUS: tuple[str, ...] = (
    "rkaf:fresh",
    "rkaf:stale",
    "rkaf:notCached",
)

#: `#ConceptResolutionMethod` — constraints/core/concept-resolution-result.cue
CONCEPT_RESOLUTION_METHOD: tuple[str, ...] = (
    "rkaf:directRegistry",
    "rkaf:exactMatchTrusted",
    "rkaf:closeMatchLocallyAdopted",
    "rkaf:closeMatchAwaitingAdoption",
    "rkaf:broadOrNarrowMatchDiscoveryOnly",
    "rkaf:cacheServed",
    "rkaf:staleCacheServed",
)

#: `#ConceptResolutionStatus` — constraints/core/concept-resolution-result.cue
CONCEPT_RESOLUTION_STATUS: tuple[str, ...] = (
    "rkaf:resolved",
    "rkaf:unresolved",
    "rkaf:ambiguous",
    "rkaf:conflicting",
    "rkaf:registryUnavailable",
    "rkaf:staleCacheFallback",
)

#: `#ConfidenceMethod` — constraints/core/confidence-record.cue
CONFIDENCE_METHOD: tuple[str, ...] = (
    "rkaf:model-inference",
    "rkaf:human-estimation",
    "rkaf:review-consensus",
    "rkaf:source-class-inheritance",
    "rkaf:rule-based",
)

#: `#ConflictSeverity` — constraints/core/registry-conflict.cue
CONFLICT_SEVERITY: tuple[str, ...] = (
    "rkaf:informational",
    "rkaf:operationalConflict",
    "rkaf:publicationBlocking",
    "rkaf:authorityCritical",
)

#: `#ConsumerLifecycleState` — constraints/core/generated-work-product.cue
CONSUMER_LIFECYCLE_STATE: tuple[str, ...] = (
    "rkaf:draft",
    "rkaf:proposedForOperational",
    "rkaf:operational",
    "rkaf:staleForCurrentUse",
    "rkaf:published",
)

#: `#CoordinateSystem` — constraints/core/source-fragment.cue
COORDINATE_SYSTEM: tuple[str, ...] = (
    "rkaf:unicode-codepoint",
    "rkaf:utf8-byte",
    "rkaf:utf16-code-unit",
    "rkaf:xml-node-path",
    "rkaf:page-region",
    "rkaf:partner-defined",
)

#: `#DocketIdentifierScheme` — constraints/profiles/us-rulemaking/rulemaking.cue
DOCKET_IDENTIFIER_SCHEME: tuple[str, ...] = (
    "rkaf:us-regsgov",
    "rkaf:official-registry",
    "rkaf:partner-defined",
)

#: `#EpistemicBasis` — constraints/core/assertion.cue
EPISTEMIC_BASIS: tuple[str, ...] = (
    "rkaf:sourceExplicit",
    "rkaf:deterministicDerivation",
    "rkaf:statisticalInference",
    "rkaf:editorialAssertion",
    "rkaf:userAssertion",
)

#: `#EvaluationAnchor` — constraints/core/evaluation-anchor.cue
EVALUATION_ANCHOR: tuple[str, ...] = (
    "rkaf:applicationSubmissionTime",
    "rkaf:eventOccurrenceTime",
    "rkaf:eligibilityDeterminationTime",
    "rkaf:noticeGenerationTime",
    "rkaf:workflowStartTime",
    "rkaf:workflowStepStartTime",
    "rkaf:currentTime",
    "rkaf:effectivePeriodStart",
    "rkaf:publicationTime",
)

#: `#EvidenceRole` — constraints/core/evidence-binding.cue
EVIDENCE_ROLE: tuple[str, ...] = (
    "rkaf:textualEvidence",
    "rkaf:structuralEvidence",
    "rkaf:retrievalSignal",
    "rkaf:authorityCitation",
    "rkaf:officialSourceMetadata",
    "rkaf:reviewedAuthorityChain",
    "rkaf:formalAdoptionEvent",
    "rkaf:mappingRationale",
    "rkaf:registrationEvent",
    "rkaf:rescissionEvidence",
)

#: `#EvidentiaryFunction` — constraints/core/evidence-binding.cue
EVIDENTIARY_FUNCTION: tuple[str, ...] = (
    "rkaf:supports",
    "rkaf:qualifies",
    "rkaf:contradicts",
    "rkaf:definesScope",
    "rkaf:providesContext",
)

#: `#ExtractionMethod` — constraints/core/extraction-activity.cue
EXTRACTION_METHOD: tuple[str, ...] = (
    "rkaf:deterministicParse",
    "rkaf:ruleBasedExtraction",
    "rkaf:modelExtraction",
    "rkaf:humanExtraction",
    "rkaf:importedRecord",
)

#: `#FindingKind` — constraints/core/finding.cue
FINDING_KIND: tuple[str, ...] = (
    "rkaf:warning",
    "rkaf:error",
    "rkaf:staleDependency",
    "rkaf:registryUnavailable",
    "rkaf:registryVersionOutOfRange",
    "rkaf:conceptConflict",
    "rkaf:authorityBroken",
    "rkaf:unsupportedAnchor",
    "rkaf:other",
)

#: `#FindingSeverity` — constraints/core/finding.cue
FINDING_SEVERITY: tuple[str, ...] = (
    "rkaf:informational",
    "rkaf:operationalConflict",
    "rkaf:publicationBlocking",
    "rkaf:authorityCritical",
)

#: `#FragmentIdentityScheme` — constraints/core/source-fragment.cue
FRAGMENT_IDENTITY_SCHEME: tuple[str, ...] = (
    "rkaf:published-fragment",
    "rkaf:carrier-local-fragment",
)

#: `#GateStatus` — constraints/analysis/resolver-proof-record.cue
GATE_STATUS: tuple[str, ...] = (
    "rkaf:gatePass",
    "rkaf:gateFail",
    "rkaf:gateUnknown",
)

#: `#LifecycleEventKind` — constraints/core/lifecycle-event.cue
LIFECYCLE_EVENT_KIND: tuple[str, ...] = (
    "rkaf:revalidation",
    "rkaf:revalidationClosure",
    "rkaf:amendment",
    "rkaf:supersession",
    "rkaf:rescission",
    "rkaf:materialRevision",
    "rkaf:editorialRevision",
    "rkaf:conceptLifecycle",
)

#: `#LocalAdoptionAuthorityKind` — constraints/core/local-adoption.cue
LOCAL_ADOPTION_AUTHORITY_KIND: tuple[str, ...] = (
    "rkaf:organizational",
    "rkaf:localOperational",
    "rkaf:contractual",
    "rkaf:publication",
)

#: `#MachineAdjudicationVerdict` — constraints/analysis/machine-adjudication.cue
MACHINE_ADJUDICATION_VERDICT: tuple[str, ...] = (
    "rkaf:verdictSame",
    "rkaf:verdictNearSame",
    "rkaf:verdictTargetBroader",
    "rkaf:verdictTargetNarrower",
    "rkaf:verdictRelated",
)

#: `#MappingState` — constraints/core/mapping-state.cue
MAPPING_STATE: tuple[str, ...] = (
    "rkaf:mapsToWos",
    "rkaf:authoringOnly",
    "rkaf:requiresSpecExtension",
    "rkaf:unmappedButApproved",
)

#: `#NoEvidenceReason` — constraints/core/evidence-binding.cue
NO_EVIDENCE_REASON: tuple[str, ...] = (
    "rkaf:axiomatic",
    "rkaf:inferred-from-warrant-class",
    "rkaf:consensus-without-citation",
    "rkaf:permitted-by-safety-label",
    "rkaf:declared-hypothesis",
)

#: `#ProceedingIdentifierScheme` — constraints/profiles/us-rulemaking/rulemaking.cue
PROCEEDING_IDENTIFIER_SCHEME: tuple[str, ...] = (
    "rkaf:official-registry",
    "rkaf:partner-defined",
)

#: `#ProceedingStage` — constraints/profiles/us-rulemaking/rulemaking.cue
PROCEEDING_STAGE: tuple[str, ...] = (
    "rkaf:proceedingPrerule",
    "rkaf:proceedingProposed",
    "rkaf:proceedingSupplemental",
    "rkaf:proceedingFinal",
    "rkaf:proceedingWithdrawn",
    "rkaf:proceedingLongterm",
    "rkaf:proceedingConcluded",
)

#: `#ProceedingTerminationCause` — constraints/profiles/us-rulemaking/rulemaking.cue
PROCEEDING_TERMINATION_CAUSE: tuple[str, ...] = (
    "rkaf:agencyWithdrawal",
    "rkaf:judicialVacatur",
    "rkaf:congressionalDisapproval",
    "rkaf:administrativeConclusion",
)

#: `#ProvisionalAIUsageEligibility` — constraints/core/assertion.cue
PROVISIONAL_AI_USAGE_ELIGIBILITY: tuple[str, ...] = (
    "rkaf:notEligible",
    "rkaf:searchOnly",
    "rkaf:reviewQueueOnly",
)

#: `#ReferenceResourceMembershipMode` — constraints/core/reference-resource-release.cue
REFERENCE_RESOURCE_MEMBERSHIP_MODE: tuple[str, ...] = (
    "rkaf:completeMembership",
    "rkaf:partialMembership",
    "rkaf:membershipNotEnumerated",
)

#: `#ReferenceResourceVersionBasis` — constraints/core/reference-resource-release.cue
REFERENCE_RESOURCE_VERSION_BASIS: tuple[str, ...] = (
    "rkaf:publisherAssigned",
    "rkaf:contentDerived",
)

#: `#RegulatoryClass` — constraints/core/access-scope.cue
REGULATORY_CLASS: tuple[str, ...] = (
    "rkaf:HIPAA-PHI",
    "rkaf:GDPR-PII",
    "rkaf:FERPA",
    "rkaf:CJIS",
    "rkaf:classified",
    "rkaf:legally-privileged",
    "rkaf:partner-defined",
)

#: `#RelationChangeOperation` — constraints/analysis/relation-change-event.cue
RELATION_CHANGE_OPERATION: tuple[str, ...] = (
    "rkaf:relationAdoption",
    "rkaf:relationRemoval",
    "rkaf:relationSuspension",
    "rkaf:relationReplacement",
)

#: `#RelationChangeStage` — constraints/analysis/relation-change-event.cue
RELATION_CHANGE_STAGE: tuple[str, ...] = (
    "rkaf:changeProposed",
    "rkaf:changeDecided",
    "rkaf:changeEffective",
    "rkaf:changeWithdrawn",
    "rkaf:changeStageUnclear",
)

#: `#RelationComparisonOutcome` — constraints/analysis/relation-comparison-context.cue
RELATION_COMPARISON_OUTCOME: tuple[str, ...] = (
    "rkaf:comparisonSatisfied",
    "rkaf:comparisonAffirmedDeniedDiscrepancy",
    "rkaf:comparisonConflict",
    "rkaf:comparisonNotComparable",
    "rkaf:comparisonUnknown",
)

#: `#RelationFindingKind` — constraints/analysis/relation-finding.cue
RELATION_FINDING_KIND: tuple[str, ...] = (
    "rkaf:affirmedDeniedDiscrepancy",
)

#: `#ResolverProofOutcome` — constraints/analysis/resolver-proof-record.cue
RESOLVER_PROOF_OUTCOME: tuple[str, ...] = (
    "rkaf:gatePass",
    "rkaf:gateFail",
    "rkaf:gateUnknown",
    "rkaf:scopeEquivalent",
    "rkaf:scopeObservedSubsumesExpected",
    "rkaf:scopeObservedNarrowsExpected",
    "rkaf:scopeOverlaps",
    "rkaf:scopeDisjoint",
    "rkaf:scopeUnknown",
)

#: `#ResolverProofType` — constraints/analysis/resolver-proof-record.cue
RESOLVER_PROOF_TYPE: tuple[str, ...] = (
    "rkaf:predicateCatalogProof",
    "rkaf:assertionStateProof",
    "rkaf:evidenceBindingProof",
    "rkaf:baselineWarrantProof",
    "rkaf:artifactPairingProof",
    "rkaf:scopeComparisonProof",
    "rkaf:machineAdjudicationProof",
)

#: `#RetentionPostExpiry` — constraints/core/retention-policy.cue
RETENTION_POST_EXPIRY: tuple[str, ...] = (
    "rkaf:delete",
    "rkaf:anonymize",
    "rkaf:archive",
    "rkaf:legal-hold-on-trigger",
)

#: `#RetentionTrigger` — constraints/core/retention-policy.cue
RETENTION_TRIGGER: tuple[str, ...] = (
    "rkaf:creation",
    "rkaf:lastAccess",
    "rkaf:lastModification",
    "rkaf:lifecycleEvent",
)

#: `#RevalidationClosureDecision` — constraints/core/revalidation-event.cue
REVALIDATION_CLOSURE_DECISION: tuple[str, ...] = (
    "rkaf:revalidated",
    "rkaf:supersededBySuccessor",
    "rkaf:retainedForPointInTime",
    "rkaf:retired",
)

#: `#SafetyLabel` — constraints/core/trust-and-safety.cue
SAFETY_LABEL: tuple[str, ...] = (
    "rkaf:D0DisplayOnly",
    "rkaf:S1Suggestion",
    "rkaf:R2Review",
    "rkaf:A3Advisory",
    "rkaf:A3AdvisoryAggregated",
    "rkaf:A3AuthorityCritical",
    "rkaf:P4Production",
    "rkaf:permits-axiomatic",
    "rkaf:permits-consensus-without-citation",
    "rkaf:permits-all",
)

#: `#SafetyLabelPermitsConsensus` — constraints/adversarial/conditional-silent-pass.cue
SAFETY_LABEL_PERMITS_CONSENSUS: tuple[str, ...] = (
    "rkaf:permits-consensus-without-citation",
    "rkaf:permits-axiomatic",
    "rkaf:permits-all",
)

#: `#ScopeRelation` — constraints/analysis/resolver-proof-record.cue
SCOPE_RELATION: tuple[str, ...] = (
    "rkaf:scopeEquivalent",
    "rkaf:scopeObservedSubsumesExpected",
    "rkaf:scopeObservedNarrowsExpected",
    "rkaf:scopeOverlaps",
    "rkaf:scopeDisjoint",
    "rkaf:scopeUnknown",
)

#: `#ScoreCategorical` — constraints/core/confidence-record.cue
SCORE_CATEGORICAL: tuple[str, ...] = (
    "rkaf:very-low",
    "rkaf:low",
    "rkaf:medium",
    "rkaf:high",
    "rkaf:very-high",
)

#: `#SelectorKind` — constraints/core/source-fragment.cue
SELECTOR_KIND: tuple[str, ...] = (
    "oa:FragmentSelector",
    "oa:TextQuoteSelector",
    "oa:TextPositionSelector",
    "oa:RangeSelector",
    "oa:XPathSelector",
    "oa:CssSelector",
    "rkaf:aknt-eId",
    "rkaf:uslm-section",
    "rkaf:eli-fragment",
    "rkaf:jsonpath",
    "rkaf:doi-fragment",
    "rkaf:partner-defined",
)

#: `#SkosMappingPredicate` — constraints/core/concept-mapping.cue
SKOS_MAPPING_PREDICATE: tuple[str, ...] = (
    "skos:exactMatch",
    "skos:closeMatch",
    "skos:broadMatch",
    "skos:narrowMatch",
    "skos:relatedMatch",
)

#: `#UsageEligibility` — constraints/core/usage-eligibility.cue
USAGE_ELIGIBILITY: tuple[str, ...] = (
    "rkaf:notEligible",
    "rkaf:searchOnly",
    "rkaf:reviewQueueOnly",
    "rkaf:draftGenerationAllowed",
    "rkaf:localOperationalUse",
    "rkaf:publicationAllowed",
    "rkaf:officialUse",
)

#: `#USProceedingLifecycleEventKind` — constraints/profiles/us-rulemaking/us-lifecycle-event.cue
US_PROCEEDING_LIFECYCLE_EVENT_KIND: tuple[str, ...] = (
    "rkaf:proceedingPrerule",
    "rkaf:proceedingProposed",
    "rkaf:proceedingSupplemental",
    "rkaf:proceedingFinal",
    "rkaf:proceedingWithdrawn",
    "rkaf:proceedingLongterm",
    "rkaf:proceedingConcluded",
    "rkaf:proceedingVacated",
    "rkaf:proceedingStayed",
    "rkaf:proceedingRemanded",
    "rkaf:proceedingReinstated",
    "rkaf:proceedingDisapproved",
)

#: `#USRegulatoryIdentifierScheme` — constraints/profiles/us-rulemaking/us-regulatory-artifact.cue
US_REGULATORY_IDENTIFIER_SCHEME: tuple[str, ...] = (
    "rkaf:us-cfr",
    "rkaf:us-usc",
    "rkaf:us-frdoc",
    "rkaf:us-regsgov",
    "rkaf:us-pl",
    "rkaf:us-eo",
)

#: `#ValueDatatype` — constraints/core/value-assertion.cue
VALUE_DATATYPE: tuple[str, ...] = (
    "xsd:string",
    "xsd:token",
    "xsd:boolean",
    "xsd:integer",
    "xsd:decimal",
    "xsd:double",
    "xsd:date",
    "xsd:dateTime",
    "xsd:time",
    "xsd:duration",
    "xsd:anyURI",
)

#: `#WarrantFamily` — constraints/core/warrant.cue
WARRANT_FAMILY: tuple[str, ...] = (
    "rkaf:legal",
    "rkaf:scientific",
    "rkaf:editorial",
    "rkaf:cryptographic",
    "rkaf:social",
    "rkaf:source-class",
)

#: `#WarrantKind` — constraints/core/warrant.cue
WARRANT_KIND: tuple[str, ...] = (
    "rkaf:legal",
    "rkaf:statutory",
    "rkaf:regulatory",
    "rkaf:delegated",
    "rkaf:organizational",
    "rkaf:contractual",
    "rkaf:localOperational",
    "rkaf:publication",
    "rkaf:methodological",
    "rkaf:empirical",
    "rkaf:replication",
    "rkaf:peerReview",
    "rkaf:editorial",
    "rkaf:factCheck",
    "rkaf:correction",
    "rkaf:cryptographic",
    "rkaf:commitment",
    "rkaf:consensus",
    "rkaf:expertOpinion",
    "rkaf:communityEndorsement",
    "rkaf:sourceReliability",
    "rkaf:provenanceClass",
)

#: `#WarrantKindCryptographic` — constraints/core/warrant.cue
WARRANT_KIND_CRYPTOGRAPHIC: tuple[str, ...] = (
    "rkaf:cryptographic",
    "rkaf:commitment",
)

#: `#WarrantKindEditorial` — constraints/core/warrant.cue
WARRANT_KIND_EDITORIAL: tuple[str, ...] = (
    "rkaf:editorial",
    "rkaf:factCheck",
    "rkaf:correction",
)

#: `#WarrantKindLegal` — constraints/core/warrant.cue
WARRANT_KIND_LEGAL: tuple[str, ...] = (
    "rkaf:legal",
    "rkaf:statutory",
    "rkaf:regulatory",
    "rkaf:delegated",
    "rkaf:organizational",
    "rkaf:contractual",
    "rkaf:localOperational",
    "rkaf:publication",
)

#: `#WarrantKindScientific` — constraints/core/warrant.cue
WARRANT_KIND_SCIENTIFIC: tuple[str, ...] = (
    "rkaf:methodological",
    "rkaf:empirical",
    "rkaf:replication",
    "rkaf:peerReview",
)

#: `#WarrantKindSocial` — constraints/core/warrant.cue
WARRANT_KIND_SOCIAL: tuple[str, ...] = (
    "rkaf:consensus",
    "rkaf:expertOpinion",
    "rkaf:communityEndorsement",
)

#: `#WarrantKindSourceClass` — constraints/core/warrant.cue
WARRANT_KIND_SOURCE_CLASS: tuple[str, ...] = (
    "rkaf:sourceReliability",
    "rkaf:provenanceClass",
)

#: `#WarrantKindV02` — constraints/adversarial/enum-drift.cue
WARRANT_KIND_V02: tuple[str, ...] = (
    "rkaf:legal",
    "rkaf:statutory",
    "rkaf:regulatory",
    "rkaf:delegated",
    "rkaf:organizational",
    "rkaf:contractual",
    "rkaf:localOperational",
    "rkaf:publication",
    "rkaf:methodological",
    "rkaf:empirical",
    "rkaf:replication",
    "rkaf:peerReview",
    "rkaf:editorial",
    "rkaf:factCheck",
    "rkaf:correction",
    "rkaf:cryptographic",
    "rkaf:commitment",
    "rkaf:consensus",
    "rkaf:expertOpinion",
    "rkaf:communityEndorsement",
    "rkaf:sourceReliability",
    "rkaf:provenanceClass",
)

#: Every enum by its CUE definition name.
ENUMS: dict[str, tuple[str, ...]] = {
    "AccessScopeKind": ACCESS_SCOPE_KIND,
    "AgendaItemIdentifierScheme": AGENDA_ITEM_IDENTIFIER_SCHEME,
    "AgendaObservationIdentifierScheme": AGENDA_OBSERVATION_IDENTIFIER_SCHEME,
    "AgendaPriority": AGENDA_PRIORITY,
    "AgendaScopeStatus": AGENDA_SCOPE_STATUS,
    "AgendaStage": AGENDA_STAGE,
    "ArtifactIdentifierScheme": ARTIFACT_IDENTIFIER_SCHEME,
    "AssertionOrigin": ASSERTION_ORIGIN,
    "AssertionPolarity": ASSERTION_POLARITY,
    "AttestationDecision": ATTESTATION_DECISION,
    "AttestorKind": ATTESTOR_KIND,
    "AuthorityChainStatus": AUTHORITY_CHAIN_STATUS,
    "AuthorityKind": AUTHORITY_KIND,
    "BridgeIssueKind": BRIDGE_ISSUE_KIND,
    "BridgeResult": BRIDGE_RESULT,
    "CalibrationStatus": CALIBRATION_STATUS,
    "ClaimantAttribution": CLAIMANT_ATTRIBUTION,
    "ClosureClaimStatus": CLOSURE_CLAIM_STATUS,
    "ComposedLifecycleEventKind": COMPOSED_LIFECYCLE_EVENT_KIND,
    "ConceptAssignmentPredicate": CONCEPT_ASSIGNMENT_PREDICATE,
    "ConceptLifecycleOperation": CONCEPT_LIFECYCLE_OPERATION,
    "ConceptResolutionCacheStatus": CONCEPT_RESOLUTION_CACHE_STATUS,
    "ConceptResolutionMethod": CONCEPT_RESOLUTION_METHOD,
    "ConceptResolutionStatus": CONCEPT_RESOLUTION_STATUS,
    "ConfidenceMethod": CONFIDENCE_METHOD,
    "ConflictSeverity": CONFLICT_SEVERITY,
    "ConsumerLifecycleState": CONSUMER_LIFECYCLE_STATE,
    "CoordinateSystem": COORDINATE_SYSTEM,
    "DocketIdentifierScheme": DOCKET_IDENTIFIER_SCHEME,
    "EpistemicBasis": EPISTEMIC_BASIS,
    "EvaluationAnchor": EVALUATION_ANCHOR,
    "EvidenceRole": EVIDENCE_ROLE,
    "EvidentiaryFunction": EVIDENTIARY_FUNCTION,
    "ExtractionMethod": EXTRACTION_METHOD,
    "FindingKind": FINDING_KIND,
    "FindingSeverity": FINDING_SEVERITY,
    "FragmentIdentityScheme": FRAGMENT_IDENTITY_SCHEME,
    "GateStatus": GATE_STATUS,
    "LifecycleEventKind": LIFECYCLE_EVENT_KIND,
    "LocalAdoptionAuthorityKind": LOCAL_ADOPTION_AUTHORITY_KIND,
    "MachineAdjudicationVerdict": MACHINE_ADJUDICATION_VERDICT,
    "MappingState": MAPPING_STATE,
    "NoEvidenceReason": NO_EVIDENCE_REASON,
    "ProceedingIdentifierScheme": PROCEEDING_IDENTIFIER_SCHEME,
    "ProceedingStage": PROCEEDING_STAGE,
    "ProceedingTerminationCause": PROCEEDING_TERMINATION_CAUSE,
    "ProvisionalAIUsageEligibility": PROVISIONAL_AI_USAGE_ELIGIBILITY,
    "ReferenceResourceMembershipMode": REFERENCE_RESOURCE_MEMBERSHIP_MODE,
    "ReferenceResourceVersionBasis": REFERENCE_RESOURCE_VERSION_BASIS,
    "RegulatoryClass": REGULATORY_CLASS,
    "RelationChangeOperation": RELATION_CHANGE_OPERATION,
    "RelationChangeStage": RELATION_CHANGE_STAGE,
    "RelationComparisonOutcome": RELATION_COMPARISON_OUTCOME,
    "RelationFindingKind": RELATION_FINDING_KIND,
    "ResolverProofOutcome": RESOLVER_PROOF_OUTCOME,
    "ResolverProofType": RESOLVER_PROOF_TYPE,
    "RetentionPostExpiry": RETENTION_POST_EXPIRY,
    "RetentionTrigger": RETENTION_TRIGGER,
    "RevalidationClosureDecision": REVALIDATION_CLOSURE_DECISION,
    "SafetyLabel": SAFETY_LABEL,
    "SafetyLabelPermitsConsensus": SAFETY_LABEL_PERMITS_CONSENSUS,
    "ScopeRelation": SCOPE_RELATION,
    "ScoreCategorical": SCORE_CATEGORICAL,
    "SelectorKind": SELECTOR_KIND,
    "SkosMappingPredicate": SKOS_MAPPING_PREDICATE,
    "USProceedingLifecycleEventKind": US_PROCEEDING_LIFECYCLE_EVENT_KIND,
    "USRegulatoryIdentifierScheme": US_REGULATORY_IDENTIFIER_SCHEME,
    "UsageEligibility": USAGE_ELIGIBILITY,
    "ValueDatatype": VALUE_DATATYPE,
    "WarrantFamily": WARRANT_FAMILY,
    "WarrantKind": WARRANT_KIND,
    "WarrantKindCryptographic": WARRANT_KIND_CRYPTOGRAPHIC,
    "WarrantKindEditorial": WARRANT_KIND_EDITORIAL,
    "WarrantKindLegal": WARRANT_KIND_LEGAL,
    "WarrantKindScientific": WARRANT_KIND_SCIENTIFIC,
    "WarrantKindSocial": WARRANT_KIND_SOCIAL,
    "WarrantKindSourceClass": WARRANT_KIND_SOURCE_CLASS,
    "WarrantKindV02": WARRANT_KIND_V02,
}

#: Where each enum is declared, for the consumer that has to go read it.
ENUM_SOURCES: dict[str, str] = {
    "AccessScopeKind": "constraints/core/access-scope.cue",
    "AgendaItemIdentifierScheme": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "AgendaObservationIdentifierScheme": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "AgendaPriority": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "AgendaScopeStatus": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "AgendaStage": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "ArtifactIdentifierScheme": "constraints/core/artifact.cue",
    "AssertionOrigin": "constraints/core/assertion.cue",
    "AssertionPolarity": "constraints/core/assertion.cue",
    "AttestationDecision": "constraints/core/attestation.cue",
    "AttestorKind": "constraints/core/attestation.cue",
    "AuthorityChainStatus": "constraints/core/bridge-validation-result.cue",
    "AuthorityKind": "constraints/core/authority.cue",
    "BridgeIssueKind": "constraints/core/bridge-issue-attestation-contract.cue",
    "BridgeResult": "constraints/core/bridge-validation-result.cue",
    "CalibrationStatus": "constraints/core/confidence-record.cue",
    "ClaimantAttribution": "constraints/core/source-claimant.cue",
    "ClosureClaimStatus": "constraints/analysis/closure-claim.cue",
    "ComposedLifecycleEventKind": "constraints/profiles/us-rulemaking/us-lifecycle-event.cue",
    "ConceptAssignmentPredicate": "constraints/core/concept-assignment.cue",
    "ConceptLifecycleOperation": "constraints/core/lifecycle-event.cue",
    "ConceptResolutionCacheStatus": "constraints/core/concept-resolution-result.cue",
    "ConceptResolutionMethod": "constraints/core/concept-resolution-result.cue",
    "ConceptResolutionStatus": "constraints/core/concept-resolution-result.cue",
    "ConfidenceMethod": "constraints/core/confidence-record.cue",
    "ConflictSeverity": "constraints/core/registry-conflict.cue",
    "ConsumerLifecycleState": "constraints/core/generated-work-product.cue",
    "CoordinateSystem": "constraints/core/source-fragment.cue",
    "DocketIdentifierScheme": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "EpistemicBasis": "constraints/core/assertion.cue",
    "EvaluationAnchor": "constraints/core/evaluation-anchor.cue",
    "EvidenceRole": "constraints/core/evidence-binding.cue",
    "EvidentiaryFunction": "constraints/core/evidence-binding.cue",
    "ExtractionMethod": "constraints/core/extraction-activity.cue",
    "FindingKind": "constraints/core/finding.cue",
    "FindingSeverity": "constraints/core/finding.cue",
    "FragmentIdentityScheme": "constraints/core/source-fragment.cue",
    "GateStatus": "constraints/analysis/resolver-proof-record.cue",
    "LifecycleEventKind": "constraints/core/lifecycle-event.cue",
    "LocalAdoptionAuthorityKind": "constraints/core/local-adoption.cue",
    "MachineAdjudicationVerdict": "constraints/analysis/machine-adjudication.cue",
    "MappingState": "constraints/core/mapping-state.cue",
    "NoEvidenceReason": "constraints/core/evidence-binding.cue",
    "ProceedingIdentifierScheme": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "ProceedingStage": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "ProceedingTerminationCause": "constraints/profiles/us-rulemaking/rulemaking.cue",
    "ProvisionalAIUsageEligibility": "constraints/core/assertion.cue",
    "ReferenceResourceMembershipMode": "constraints/core/reference-resource-release.cue",
    "ReferenceResourceVersionBasis": "constraints/core/reference-resource-release.cue",
    "RegulatoryClass": "constraints/core/access-scope.cue",
    "RelationChangeOperation": "constraints/analysis/relation-change-event.cue",
    "RelationChangeStage": "constraints/analysis/relation-change-event.cue",
    "RelationComparisonOutcome": "constraints/analysis/relation-comparison-context.cue",
    "RelationFindingKind": "constraints/analysis/relation-finding.cue",
    "ResolverProofOutcome": "constraints/analysis/resolver-proof-record.cue",
    "ResolverProofType": "constraints/analysis/resolver-proof-record.cue",
    "RetentionPostExpiry": "constraints/core/retention-policy.cue",
    "RetentionTrigger": "constraints/core/retention-policy.cue",
    "RevalidationClosureDecision": "constraints/core/revalidation-event.cue",
    "SafetyLabel": "constraints/core/trust-and-safety.cue",
    "SafetyLabelPermitsConsensus": "constraints/adversarial/conditional-silent-pass.cue",
    "ScopeRelation": "constraints/analysis/resolver-proof-record.cue",
    "ScoreCategorical": "constraints/core/confidence-record.cue",
    "SelectorKind": "constraints/core/source-fragment.cue",
    "SkosMappingPredicate": "constraints/core/concept-mapping.cue",
    "USProceedingLifecycleEventKind": "constraints/profiles/us-rulemaking/us-lifecycle-event.cue",
    "USRegulatoryIdentifierScheme": "constraints/profiles/us-rulemaking/us-regulatory-artifact.cue",
    "UsageEligibility": "constraints/core/usage-eligibility.cue",
    "ValueDatatype": "constraints/core/value-assertion.cue",
    "WarrantFamily": "constraints/core/warrant.cue",
    "WarrantKind": "constraints/core/warrant.cue",
    "WarrantKindCryptographic": "constraints/core/warrant.cue",
    "WarrantKindEditorial": "constraints/core/warrant.cue",
    "WarrantKindLegal": "constraints/core/warrant.cue",
    "WarrantKindScientific": "constraints/core/warrant.cue",
    "WarrantKindSocial": "constraints/core/warrant.cue",
    "WarrantKindSourceClass": "constraints/core/warrant.cue",
    "WarrantKindV02": "constraints/adversarial/enum-drift.cue",
}

__all__ = [
    "ENUMS",
    "ENUM_SOURCES",
    "ACCESS_SCOPE_KIND",
    "AGENDA_ITEM_IDENTIFIER_SCHEME",
    "AGENDA_OBSERVATION_IDENTIFIER_SCHEME",
    "AGENDA_PRIORITY",
    "AGENDA_SCOPE_STATUS",
    "AGENDA_STAGE",
    "ARTIFACT_IDENTIFIER_SCHEME",
    "ASSERTION_ORIGIN",
    "ASSERTION_POLARITY",
    "ATTESTATION_DECISION",
    "ATTESTOR_KIND",
    "AUTHORITY_CHAIN_STATUS",
    "AUTHORITY_KIND",
    "BRIDGE_ISSUE_KIND",
    "BRIDGE_RESULT",
    "CALIBRATION_STATUS",
    "CLAIMANT_ATTRIBUTION",
    "CLOSURE_CLAIM_STATUS",
    "COMPOSED_LIFECYCLE_EVENT_KIND",
    "CONCEPT_ASSIGNMENT_PREDICATE",
    "CONCEPT_LIFECYCLE_OPERATION",
    "CONCEPT_RESOLUTION_CACHE_STATUS",
    "CONCEPT_RESOLUTION_METHOD",
    "CONCEPT_RESOLUTION_STATUS",
    "CONFIDENCE_METHOD",
    "CONFLICT_SEVERITY",
    "CONSUMER_LIFECYCLE_STATE",
    "COORDINATE_SYSTEM",
    "DOCKET_IDENTIFIER_SCHEME",
    "EPISTEMIC_BASIS",
    "EVALUATION_ANCHOR",
    "EVIDENCE_ROLE",
    "EVIDENTIARY_FUNCTION",
    "EXTRACTION_METHOD",
    "FINDING_KIND",
    "FINDING_SEVERITY",
    "FRAGMENT_IDENTITY_SCHEME",
    "GATE_STATUS",
    "LIFECYCLE_EVENT_KIND",
    "LOCAL_ADOPTION_AUTHORITY_KIND",
    "MACHINE_ADJUDICATION_VERDICT",
    "MAPPING_STATE",
    "NO_EVIDENCE_REASON",
    "PROCEEDING_IDENTIFIER_SCHEME",
    "PROCEEDING_STAGE",
    "PROCEEDING_TERMINATION_CAUSE",
    "PROVISIONAL_AI_USAGE_ELIGIBILITY",
    "REFERENCE_RESOURCE_MEMBERSHIP_MODE",
    "REFERENCE_RESOURCE_VERSION_BASIS",
    "REGULATORY_CLASS",
    "RELATION_CHANGE_OPERATION",
    "RELATION_CHANGE_STAGE",
    "RELATION_COMPARISON_OUTCOME",
    "RELATION_FINDING_KIND",
    "RESOLVER_PROOF_OUTCOME",
    "RESOLVER_PROOF_TYPE",
    "RETENTION_POST_EXPIRY",
    "RETENTION_TRIGGER",
    "REVALIDATION_CLOSURE_DECISION",
    "SAFETY_LABEL",
    "SAFETY_LABEL_PERMITS_CONSENSUS",
    "SCOPE_RELATION",
    "SCORE_CATEGORICAL",
    "SELECTOR_KIND",
    "SKOS_MAPPING_PREDICATE",
    "USAGE_ELIGIBILITY",
    "US_PROCEEDING_LIFECYCLE_EVENT_KIND",
    "US_REGULATORY_IDENTIFIER_SCHEME",
    "VALUE_DATATYPE",
    "WARRANT_FAMILY",
    "WARRANT_KIND",
    "WARRANT_KIND_CRYPTOGRAPHIC",
    "WARRANT_KIND_EDITORIAL",
    "WARRANT_KIND_LEGAL",
    "WARRANT_KIND_SCIENTIFIC",
    "WARRANT_KIND_SOCIAL",
    "WARRANT_KIND_SOURCE_CLASS",
    "WARRANT_KIND_V02",
]
