# GENERATED by tools/build_contract_exports.py — do not edit.
#
# Sources are listed in tools/build_contract_exports.py, which also records
# what is deliberately not a source and why.
"""Every rkaf term Rulespec declares, as an attribute of this module.

    from rulespec_conformance.contract.terms import hasContentDigest

An unknown name — a rename not followed, a term retired, a typo — is an
ImportError or an AttributeError at import time, not a string that
validates as a string and fails at the far end of a pipeline. That is the
whole point of the module: the check is the import.

Attribute names are the term's local name, with `-` written `_`:
`rkaf:us-cfr` is `us_cfr`. The VALUE is always the exact compact IRI, and
it is a `Term`, so `.iri` expands it and everything else treats it as the
`str` it is.
"""

from __future__ import annotations

from ._term import RKAF_NAMESPACE as RKAF_NAMESPACE
from ._term import Term as Term

A3Advisory = Term("rkaf:A3Advisory")
A3AdvisoryAggregated = Term("rkaf:A3AdvisoryAggregated")
A3AuthorityCritical = Term("rkaf:A3AuthorityCritical")
AILineage = Term("rkaf:AILineage")
AccessScope = Term("rkaf:AccessScope")
AccessScopeKind = Term("rkaf:AccessScopeKind")
AgendaItemIdentifierScheme = Term("rkaf:AgendaItemIdentifierScheme")
AgendaPriority = Term("rkaf:AgendaPriority")
AgendaProceedingRelationship = Term("rkaf:AgendaProceedingRelationship")
AgendaScopeStatus = Term("rkaf:AgendaScopeStatus")
AgendaStage = Term("rkaf:AgendaStage")
ApplicabilityScope = Term("rkaf:ApplicabilityScope")
Artifact = Term("rkaf:Artifact")
ArtifactIdentifierScheme = Term("rkaf:ArtifactIdentifierScheme")
Assertion = Term("rkaf:Assertion")
AssertionOrigin = Term("rkaf:AssertionOrigin")
AssertionPolarity = Term("rkaf:AssertionPolarity")
Attestation = Term("rkaf:Attestation")
Authority = Term("rkaf:Authority")
AuthorityKindSubstitution = Term("rkaf:AuthorityKindSubstitution")
BehaviorTestCase = Term("rkaf:BehaviorTestCase")
BridgeConsumerRegistration = Term("rkaf:BridgeConsumerRegistration")
BridgeContractRule = Term("rkaf:BridgeContractRule")
BridgeIssueAttestationContract = Term("rkaf:BridgeIssueAttestationContract")
BridgeValidationResult = Term("rkaf:BridgeValidationResult")
CJIS = Term("rkaf:CJIS")
CalibrationStatus = Term("rkaf:CalibrationStatus")
CascadeClosureV1 = Term("rkaf:CascadeClosureV1")
ClaimantAttribution = Term("rkaf:ClaimantAttribution")
ClosureClaim = Term("rkaf:ClosureClaim")
ClosureClaimStatus = Term("rkaf:ClosureClaimStatus")
CommentPeriod = Term("rkaf:CommentPeriod")
Concept = Term("rkaf:Concept")
ConceptAssignment = Term("rkaf:ConceptAssignment")
ConceptAssignmentPredicate = Term("rkaf:ConceptAssignmentPredicate")
ConceptLifecycleOperation = Term("rkaf:ConceptLifecycleOperation")
ConceptMapping = Term("rkaf:ConceptMapping")
ConceptMintingAuthority = Term("rkaf:ConceptMintingAuthority")
ConceptRegistry = Term("rkaf:ConceptRegistry")
ConceptResolutionCacheStatus = Term("rkaf:ConceptResolutionCacheStatus")
ConceptResolutionMethod = Term("rkaf:ConceptResolutionMethod")
ConceptResolutionResult = Term("rkaf:ConceptResolutionResult")
ConceptResolutionStatus = Term("rkaf:ConceptResolutionStatus")
ConceptResolutionWithConflict = Term("rkaf:ConceptResolutionWithConflict")
ConceptScheme = Term("rkaf:ConceptScheme")
ConceptUsedAsAuthority = Term("rkaf:ConceptUsedAsAuthority")
ConfidenceMethod = Term("rkaf:ConfidenceMethod")
ConfidenceRecord = Term("rkaf:ConfidenceRecord")
ConsumerEffectiveDeclaration = Term("rkaf:ConsumerEffectiveDeclaration")
ConsumerLifecycleState = Term("rkaf:ConsumerLifecycleState")
ContractInternal = Term("rkaf:ContractInternal")
CoordinateSystem = Term("rkaf:CoordinateSystem")
D0DisplayOnly = Term("rkaf:D0DisplayOnly")
Docket = Term("rkaf:Docket")
DocketIdentifierScheme = Term("rkaf:DocketIdentifierScheme")
EffectivePeriod = Term("rkaf:EffectivePeriod")
EpistemicBasis = Term("rkaf:EpistemicBasis")
EvaluationAnchor = Term("rkaf:EvaluationAnchor")
EvidenceBinding = Term("rkaf:EvidenceBinding")
EvidenceRole = Term("rkaf:EvidenceRole")
EvidentiaryFunction = Term("rkaf:EvidentiaryFunction")
ExtractionActivity = Term("rkaf:ExtractionActivity")
ExtractionMethod = Term("rkaf:ExtractionMethod")
FERPA = Term("rkaf:FERPA")
Finding = Term("rkaf:Finding")
FragmentIdentityScheme = Term("rkaf:FragmentIdentityScheme")
GDPR_PII = Term("rkaf:GDPR-PII")
GateStatus = Term("rkaf:GateStatus")
GeneratedWorkProduct = Term("rkaf:GeneratedWorkProduct")
HIPAA_PHI = Term("rkaf:HIPAA-PHI")
Justification = Term("rkaf:Justification")
LLMHint = Term("rkaf:LLMHint")
LifecycleEvent = Term("rkaf:LifecycleEvent")
LocalAdoption = Term("rkaf:LocalAdoption")
LocalConcept = Term("rkaf:LocalConcept")
MachineAdjudicationProof = Term("rkaf:MachineAdjudicationProof")
MachineAdjudicationVerdict = Term("rkaf:MachineAdjudicationVerdict")
MalformedTestCase = Term("rkaf:MalformedTestCase")
MappingApplicabilityContext = Term("rkaf:MappingApplicabilityContext")
MappingState = Term("rkaf:MappingState")
MissingJustificationMetadata = Term("rkaf:MissingJustificationMetadata")
MissingNode = Term("rkaf:MissingNode")
MissingStaleTransition = Term("rkaf:MissingStaleTransition")
NoEvidenceReason = Term("rkaf:NoEvidenceReason")
OutputMismatch = Term("rkaf:OutputMismatch")
Overlay = Term("rkaf:Overlay")
P4Production = Term("rkaf:P4Production")
ParseError = Term("rkaf:ParseError")
PointInTimeException = Term("rkaf:PointInTimeException")
Proceeding = Term("rkaf:Proceeding")
ProceedingIdentifierScheme = Term("rkaf:ProceedingIdentifierScheme")
ProceedingStage = Term("rkaf:ProceedingStage")
ProceedingTerminationCause = Term("rkaf:ProceedingTerminationCause")
R2Review = Term("rkaf:R2Review")
ReferenceResourceMembershipMode = Term("rkaf:ReferenceResourceMembershipMode")
ReferenceResourceRelease = Term("rkaf:ReferenceResourceRelease")
ReferenceResourceVersionBasis = Term("rkaf:ReferenceResourceVersionBasis")
RegisteredConcept = Term("rkaf:RegisteredConcept")
RegistryConflict = Term("rkaf:RegistryConflict")
RegulatoryAgendaItem = Term("rkaf:RegulatoryAgendaItem")
RegulatoryAgendaObservation = Term("rkaf:RegulatoryAgendaObservation")
RelationChangeEvent = Term("rkaf:RelationChangeEvent")
RelationChangeOperation = Term("rkaf:RelationChangeOperation")
RelationChangeStage = Term("rkaf:RelationChangeStage")
RelationComparisonContext = Term("rkaf:RelationComparisonContext")
RelationComparisonOutcome = Term("rkaf:RelationComparisonOutcome")
RelationFinding = Term("rkaf:RelationFinding")
RelationFindingKind = Term("rkaf:RelationFindingKind")
RelationshipAssertion = Term("rkaf:RelationshipAssertion")
ResolverProofIssuer = Term("rkaf:ResolverProofIssuer")
ResolverProofRecord = Term("rkaf:ResolverProofRecord")
ResolverProofType = Term("rkaf:ResolverProofType")
RetentionPolicy = Term("rkaf:RetentionPolicy")
RevalidationClosureEvent = Term("rkaf:RevalidationClosureEvent")
RevalidationEvent = Term("rkaf:RevalidationEvent")
S1Suggestion = Term("rkaf:S1Suggestion")
ScopeRelation = Term("rkaf:ScopeRelation")
SelectorKind = Term("rkaf:SelectorKind")
SemverError = Term("rkaf:SemverError")
SkosMappingPredicate = Term("rkaf:SkosMappingPredicate")
SourceClaimant = Term("rkaf:SourceClaimant")
SourceFragment = Term("rkaf:SourceFragment")
USRegulatoryIdentifierScheme = Term("rkaf:USRegulatoryIdentifierScheme")
UnattestedConsumerIssue = Term("rkaf:UnattestedConsumerIssue")
UnauthorizedBroadening = Term("rkaf:UnauthorizedBroadening")
UnauthorizedLegalInference = Term("rkaf:UnauthorizedLegalInference")
UnsupportedContract = Term("rkaf:UnsupportedContract")
UnsupportedContractVersion = Term("rkaf:UnsupportedContractVersion")
UnsupportedEvaluationAnchor = Term("rkaf:UnsupportedEvaluationAnchor")
UnterminatedJustificationChain = Term("rkaf:UnterminatedJustificationChain")
UsageEligibility = Term("rkaf:UsageEligibility")
UsageEligibilityReducer = Term("rkaf:UsageEligibilityReducer")
ValueAssertion = Term("rkaf:ValueAssertion")
ValueDatatype = Term("rkaf:ValueDatatype")
VocabularyText = Term("rkaf:VocabularyText")
Warrant = Term("rkaf:Warrant")
WarrantFamily = Term("rkaf:WarrantFamily")
WarrantKind = Term("rkaf:WarrantKind")
Workspace = Term("rkaf:Workspace")
absorbedConcepts = Term("rkaf:absorbedConcepts")
abstained = Term("rkaf:abstained")
accepted = Term("rkaf:accepted")
acceptedDocumentTypes = Term("rkaf:acceptedDocumentTypes")
acceptedWithWarnings = Term("rkaf:acceptedWithWarnings")
accessScopeKind = Term("rkaf:accessScopeKind")
active = Term("rkaf:active")
adjudicationVerdict = Term("rkaf:adjudicationVerdict")
administrativeConclusion = Term("rkaf:administrativeConclusion")
adoptedAt = Term("rkaf:adoptedAt")
adoptionAuthorityKind = Term("rkaf:adoptionAuthorityKind")
adoptionScope = Term("rkaf:adoptionScope")
adoptionStatus = Term("rkaf:adoptionStatus")
adoptsApplicability = Term("rkaf:adoptsApplicability")
advisory = Term("rkaf:advisory")
affectedAdoption = Term("rkaf:affectedAdoption")
affectedAdoptions = Term("rkaf:affectedAdoptions")
affectedAssertions = Term("rkaf:affectedAssertions")
affectedAuthorityAssertions = Term("rkaf:affectedAuthorityAssertions")
affectedConcepts = Term("rkaf:affectedConcepts")
affectedFragments = Term("rkaf:affectedFragments")
affectedImplementationAssertions = Term("rkaf:affectedImplementationAssertions")
affectedWorkProduct = Term("rkaf:affectedWorkProduct")
affectedWorkProducts = Term("rkaf:affectedWorkProducts")
affirmed = Term("rkaf:affirmed")
affirmedDeniedDiscrepancy = Term("rkaf:affirmedDeniedDiscrepancy")
agencyWithdrawal = Term("rkaf:agencyWithdrawal")
agendaAffectsCitation = Term("rkaf:agendaAffectsCitation")
agendaAuthorityCitation = Term("rkaf:agendaAuthorityCitation")
agendaCompleted = Term("rkaf:agendaCompleted")
agendaFinal = Term("rkaf:agendaFinal")
agendaItemIdentifierScheme = Term("rkaf:agendaItemIdentifierScheme")
agendaLongterm = Term("rkaf:agendaLongterm")
agendaPrerule = Term("rkaf:agendaPrerule")
agendaPriority = Term("rkaf:agendaPriority")
agendaPriorityEconomicallySignificant = Term("rkaf:agendaPriorityEconomicallySignificant")
agendaPriorityInfoAdminOther = Term("rkaf:agendaPriorityInfoAdminOther")
agendaPriorityOtherSignificant = Term("rkaf:agendaPriorityOtherSignificant")
agendaPriorityRoutineFrequent = Term("rkaf:agendaPriorityRoutineFrequent")
agendaPrioritySubstantiveNonsignificant = Term("rkaf:agendaPrioritySubstantiveNonsignificant")
agendaProposed = Term("rkaf:agendaProposed")
agendaScopeRecurring = Term("rkaf:agendaScopeRecurring")
agendaScopeSingleObserved = Term("rkaf:agendaScopeSingleObserved")
agendaScopeStatus = Term("rkaf:agendaScopeStatus")
agendaScopeUnresolved = Term("rkaf:agendaScopeUnresolved")
agendaStage = Term("rkaf:agendaStage")
agendaTracksProceeding = Term("rkaf:agendaTracksProceeding")
aiAgent = Term("rkaf:aiAgent")
aiModel = Term("rkaf:aiModel")
aiSuggested = Term("rkaf:aiSuggested")
aknt_eId = Term("rkaf:aknt-eId")
ambiguous = Term("rkaf:ambiguous")
amendment = Term("rkaf:amendment")
anchorType = Term("rkaf:anchorType")
anchoredBy = Term("rkaf:anchoredBy")
anonymize = Term("rkaf:anonymize")
applicabilityCondition = Term("rkaf:applicabilityCondition")
applicationDomain = Term("rkaf:applicationDomain")
applicationSubmissionTime = Term("rkaf:applicationSubmissionTime")
appliesInJurisdiction = Term("rkaf:appliesInJurisdiction")
appliesTo = Term("rkaf:appliesTo")
appliesToSubject = Term("rkaf:appliesToSubject")
approved = Term("rkaf:approved")
approvedWithConditions = Term("rkaf:approvedWithConditions")
archive = Term("rkaf:archive")
artifactId = Term("rkaf:artifactId")
artifactIdentifierScheme = Term("rkaf:artifactIdentifierScheme")
artifactPairingProof = Term("rkaf:artifactPairingProof")
assertedAt = Term("rkaf:assertedAt")
assertedBy = Term("rkaf:assertedBy")
asserted_by = Term("rkaf:asserted_by")
assertion = Term("rkaf:assertion")
assertionOrigin = Term("rkaf:assertionOrigin")
assertionPolarity = Term("rkaf:assertionPolarity")
assertionStateProof = Term("rkaf:assertionStateProof")
assertsObject = Term("rkaf:assertsObject")
assertsPredicate = Term("rkaf:assertsPredicate")
assertsSubject = Term("rkaf:assertsSubject")
assertsValue = Term("rkaf:assertsValue")
assignedConceptRelease = Term("rkaf:assignedConceptRelease")
assignmentContextual = Term("rkaf:assignmentContextual")
assignmentMention = Term("rkaf:assignmentMention")
assignmentPrimary = Term("rkaf:assignmentPrimary")
assignmentSubstantive = Term("rkaf:assignmentSubstantive")
associatedWorkflowStep = Term("rkaf:associatedWorkflowStep")
attestationScope = Term("rkaf:attestationScope")
attestedAt = Term("rkaf:attestedAt")
attestedIssueKinds = Term("rkaf:attestedIssueKinds")
attestor = Term("rkaf:attestor")
attestorKind = Term("rkaf:attestorKind")
attestorType = Term("rkaf:attestorType")
attributedInFragment = Term("rkaf:attributedInFragment")
authoringOnly = Term("rkaf:authoringOnly")
authorityBroken = Term("rkaf:authorityBroken")
authorityChainStatus = Term("rkaf:authorityChainStatus")
authorityChainTraversal = Term("rkaf:authorityChainTraversal")
authorityCitation = Term("rkaf:authorityCitation")
authorityCritical = Term("rkaf:authorityCritical")
authorityKind = Term("rkaf:authorityKind")
authorizedBy = Term("rkaf:authorizedBy")
automatedParser = Term("rkaf:automatedParser")
axiomatic = Term("rkaf:axiomatic")
basedOnAttestation = Term("rkaf:basedOnAttestation")
basedOnAttestations = Term("rkaf:basedOnAttestations")
basedOnClassification = Term("rkaf:basedOnClassification")
basedOnEvent = Term("rkaf:basedOnEvent")
basedOnEvidence = Term("rkaf:basedOnEvidence")
baselineWarrantProof = Term("rkaf:baselineWarrantProof")
behaviorContract = Term("rkaf:behaviorContract")
bindsAssertion = Term("rkaf:bindsAssertion")
bindsSourceFragment = Term("rkaf:bindsSourceFragment")
bridgeContractVersion = Term("rkaf:bridgeContractVersion")
broadOrNarrowMatchDiscoveryOnly = Term("rkaf:broadOrNarrowMatchDiscoveryOnly")
broken = Term("rkaf:broken")
brokenAuthority = Term("rkaf:brokenAuthority")
brokenForNewCases = Term("rkaf:brokenForNewCases")
cacheServed = Term("rkaf:cacheServed")
cacheStatus = Term("rkaf:cacheStatus")
cachedAt = Term("rkaf:cachedAt")
calibratedAgainst = Term("rkaf:calibratedAgainst")
calibrationStatus = Term("rkaf:calibrationStatus")
capabilityCap = Term("rkaf:capabilityCap")
capturedAt = Term("rkaf:capturedAt")
capturedBy = Term("rkaf:capturedBy")
carrier_local_fragment = Term("rkaf:carrier-local-fragment")
cascadeAlgorithm = Term("rkaf:cascadeAlgorithm")
cascadeAsOf = Term("rkaf:cascadeAsOf")
cascadeSeed = Term("rkaf:cascadeSeed")
chainTerminus = Term("rkaf:chainTerminus")
chainTerminusKind = Term("rkaf:chainTerminusKind")
changeDecided = Term("rkaf:changeDecided")
changeEffective = Term("rkaf:changeEffective")
changeEvidence = Term("rkaf:changeEvidence")
changeIntendedEffectiveTime = Term("rkaf:changeIntendedEffectiveTime")
changeObject = Term("rkaf:changeObject")
changePredicate = Term("rkaf:changePredicate")
changeProposed = Term("rkaf:changeProposed")
changeStageUnclear = Term("rkaf:changeStageUnclear")
changeSubject = Term("rkaf:changeSubject")
changeWithdrawn = Term("rkaf:changeWithdrawn")
cid = Term("rkaf:cid")
claimantAttribution = Term("rkaf:claimantAttribution")
claimantIdentity = Term("rkaf:claimantIdentity")
claimantImpliedBySource = Term("rkaf:claimantImpliedBySource")
claimantIsDocumentIssuer = Term("rkaf:claimantIsDocumentIssuer")
claimantNamedInSource = Term("rkaf:claimantNamedInSource")
claimantNotStated = Term("rkaf:claimantNotStated")
claimantText = Term("rkaf:claimantText")
claimsAssertion = Term("rkaf:claimsAssertion")
classification = Term("rkaf:classification")
classified = Term("rkaf:classified")
classifiedBy = Term("rkaf:classifiedBy")
closeMatchAwaitingAdoption = Term("rkaf:closeMatchAwaitingAdoption")
closeMatchLocallyAdopted = Term("rkaf:closeMatchLocallyAdopted")
closedAt = Term("rkaf:closedAt")
closedBy = Term("rkaf:closedBy")
closesRevalidation = Term("rkaf:closesRevalidation")
closesRevalidationEvent = Term("rkaf:closesRevalidationEvent")
closureArtifact = Term("rkaf:closureArtifact")
closureClaimDisabled = Term("rkaf:closureClaimDisabled")
closureClaimStatus = Term("rkaf:closureClaimStatus")
closureDecision = Term("rkaf:closureDecision")
closureMemberDigest = Term("rkaf:closureMemberDigest")
closurePredicateFamily = Term("rkaf:closurePredicateFamily")
closureProfileVersion = Term("rkaf:closureProfileVersion")
closureRegion = Term("rkaf:closureRegion")
closureReviewedAt = Term("rkaf:closureReviewedAt")
collectsEvidenceType = Term("rkaf:collectsEvidenceType")
commentPeriodDocket = Term("rkaf:commentPeriodDocket")
commentPeriodEnd = Term("rkaf:commentPeriodEnd")
commentPeriodFor = Term("rkaf:commentPeriodFor")
commentPeriodOpenedBy = Term("rkaf:commentPeriodOpenedBy")
commentPeriodStart = Term("rkaf:commentPeriodStart")
commitment = Term("rkaf:commitment")
community = Term("rkaf:community")
communityEndorsement = Term("rkaf:communityEndorsement")
comparisonAffirmedDeniedDiscrepancy = Term("rkaf:comparisonAffirmedDeniedDiscrepancy")
comparisonBaselineArtifact = Term("rkaf:comparisonBaselineArtifact")
comparisonConflict = Term("rkaf:comparisonConflict")
comparisonConsumer = Term("rkaf:comparisonConsumer")
comparisonDetector = Term("rkaf:comparisonDetector")
comparisonDetectorVersion = Term("rkaf:comparisonDetectorVersion")
comparisonEvaluationTime = Term("rkaf:comparisonEvaluationTime")
comparisonExpectedAssertion = Term("rkaf:comparisonExpectedAssertion")
comparisonNotComparable = Term("rkaf:comparisonNotComparable")
comparisonObservedArtifact = Term("rkaf:comparisonObservedArtifact")
comparisonOutcome = Term("rkaf:comparisonOutcome")
comparisonPolicyVersion = Term("rkaf:comparisonPolicyVersion")
comparisonProofRecord = Term("rkaf:comparisonProofRecord")
comparisonSatisfied = Term("rkaf:comparisonSatisfied")
comparisonScope = Term("rkaf:comparisonScope")
comparisonSnapshot = Term("rkaf:comparisonSnapshot")
comparisonUnknown = Term("rkaf:comparisonUnknown")
completeMembership = Term("rkaf:completeMembership")
concept = Term("rkaf:concept")
conceptConflict = Term("rkaf:conceptConflict")
conceptLifecycle = Term("rkaf:conceptLifecycle")
conceptLifecycleOperation = Term("rkaf:conceptLifecycleOperation")
conceptMintingAuthority = Term("rkaf:conceptMintingAuthority")
conceptResolutionResults = Term("rkaf:conceptResolutionResults")
conceptScope = Term("rkaf:conceptScope")
confidenceBasis = Term("rkaf:confidenceBasis")
confidenceMethod = Term("rkaf:confidenceMethod")
conflicting = Term("rkaf:conflicting")
conflictingEntries = Term("rkaf:conflictingEntries")
conflictingMappings = Term("rkaf:conflictingMappings")
conflictingScope = Term("rkaf:conflictingScope")
congressionalDisapproval = Term("rkaf:congressionalDisapproval")
consensus = Term("rkaf:consensus")
consensus_without_citation = Term("rkaf:consensus-without-citation")
consumer = Term("rkaf:consumer")
consumerLifecycleState = Term("rkaf:consumerLifecycleState")
contentDerived = Term("rkaf:contentDerived")
contractRuleNumber = Term("rkaf:contractRuleNumber")
contractVersion = Term("rkaf:contractVersion")
contractual = Term("rkaf:contractual")
contradicts = Term("rkaf:contradicts")
coordinateSystem = Term("rkaf:coordinateSystem")
correction = Term("rkaf:correction")
creation = Term("rkaf:creation")
cryptographic = Term("rkaf:cryptographic")
currentTime = Term("rkaf:currentTime")
dataConcept = Term("rkaf:dataConcept")
decision = Term("rkaf:decision")
declaredAt = Term("rkaf:declaredAt")
declaredEffective = Term("rkaf:declaredEffective")
declaredScope = Term("rkaf:declaredScope")
declared_hypothesis = Term("rkaf:declared-hypothesis")
defeasible = Term("rkaf:defeasible")
definedInScope = Term("rkaf:definedInScope")
definesScope = Term("rkaf:definesScope")
delegated = Term("rkaf:delegated")
delegatedTo = Term("rkaf:delegatedTo")
delegatingAuthority = Term("rkaf:delegatingAuthority")
delete = Term("rkaf:delete")
demotion = Term("rkaf:demotion")
denied = Term("rkaf:denied")
deprecatedAt = Term("rkaf:deprecatedAt")
deprecation = Term("rkaf:deprecation")
derivedFromFragment = Term("rkaf:derivedFromFragment")
derivesAuthorityFrom = Term("rkaf:derivesAuthorityFrom")
detectedAt = Term("rkaf:detectedAt")
detectedBy = Term("rkaf:detectedBy")
detectedIssues = Term("rkaf:detectedIssues")
deterministicDerivation = Term("rkaf:deterministicDerivation")
deterministicExtraction = Term("rkaf:deterministicExtraction")
deterministicParse = Term("rkaf:deterministicParse")
directRegistry = Term("rkaf:directRegistry")
docketIdentifierScheme = Term("rkaf:docketIdentifierScheme")
doi = Term("rkaf:doi")
doi_fragment = Term("rkaf:doi-fragment")
draft = Term("rkaf:draft")
draftGenerationAllowed = Term("rkaf:draftGenerationAllowed")
editorial = Term("rkaf:editorial")
editorialAssertion = Term("rkaf:editorialAssertion")
editorialRevision = Term("rkaf:editorialRevision")
effectiveDate = Term("rkaf:effectiveDate")
effectivePeriodEnd = Term("rkaf:effectivePeriodEnd")
effectivePeriodStart = Term("rkaf:effectivePeriodStart")
effectiveUsageEligibility = Term("rkaf:effectiveUsageEligibility")
effectiveUsageEligibilityRationale = Term("rkaf:effectiveUsageEligibilityRationale")
eli = Term("rkaf:eli")
eli_dl = Term("rkaf:eli-dl")
eli_fragment = Term("rkaf:eli-fragment")
eli_i = Term("rkaf:eli-i")
eligibilityDeterminationTime = Term("rkaf:eligibilityDeterminationTime")
embargoUntil = Term("rkaf:embargoUntil")
emittedBy = Term("rkaf:emittedBy")
empirical = Term("rkaf:empirical")
endorsedForReview = Term("rkaf:endorsedForReview")
epistemicBasis = Term("rkaf:epistemicBasis")
error = Term("rkaf:error")
errorCode = Term("rkaf:errorCode")
evaluatedAgainst = Term("rkaf:evaluatedAgainst")
evaluationAnchor = Term("rkaf:evaluationAnchor")
evaluationConsumer = Term("rkaf:evaluationConsumer")
evaluationScopes = Term("rkaf:evaluationScopes")
evaluationTime = Term("rkaf:evaluationTime")
eventOccurrenceTime = Term("rkaf:eventOccurrenceTime")
evidenceBindingProof = Term("rkaf:evidenceBindingProof")
evidencePurpose = Term("rkaf:evidencePurpose")
evidenceRole = Term("rkaf:evidenceRole")
evidentiaryFunction = Term("rkaf:evidentiaryFunction")
exactMatchTrusted = Term("rkaf:exactMatchTrusted")
exceptionEffectivePeriodEnd = Term("rkaf:exceptionEffectivePeriodEnd")
exceptionEffectivePeriodStart = Term("rkaf:exceptionEffectivePeriodStart")
exceptionScope = Term("rkaf:exceptionScope")
excludesCategory = Term("rkaf:excludesCategory")
excludesPurposes = Term("rkaf:excludesPurposes")
expectedOutput = Term("rkaf:expectedOutput")
expectedRuntimeError = Term("rkaf:expectedRuntimeError")
expertOpinion = Term("rkaf:expertOpinion")
expired = Term("rkaf:expired")
extractedBy = Term("rkaf:extractedBy")
extractionAttempt = Term("rkaf:extractionAttempt")
extractionMethod = Term("rkaf:extractionMethod")
extractionModelRef = Term("rkaf:extractionModelRef")
extractionPromptRef = Term("rkaf:extractionPromptRef")
extractionRun = Term("rkaf:extractionRun")
extractorVersion = Term("rkaf:extractorVersion")
factCheck = Term("rkaf:factCheck")
findingComparedAssertion = Term("rkaf:findingComparedAssertion")
findingComparisonContext = Term("rkaf:findingComparisonContext")
findingDetectedAt = Term("rkaf:findingDetectedAt")
findingFingerprint = Term("rkaf:findingFingerprint")
findingKind = Term("rkaf:findingKind")
findingProofRecord = Term("rkaf:findingProofRecord")
findingRationale = Term("rkaf:findingRationale")
findings = Term("rkaf:findings")
flaggedForReview = Term("rkaf:flaggedForReview")
forAssertion = Term("rkaf:forAssertion")
formalAdoptionEvent = Term("rkaf:formalAdoptionEvent")
formalReviewer = Term("rkaf:formalReviewer")
formspec_need = Term("rkaf:formspec-need")
fragmentContentDigest = Term("rkaf:fragmentContentDigest")
fragmentIdentityScheme = Term("rkaf:fragmentIdentityScheme")
fragmentType = Term("rkaf:fragmentType")
fresh = Term("rkaf:fresh")
fromConcept = Term("rkaf:fromConcept")
gateFail = Term("rkaf:gateFail")
gatePass = Term("rkaf:gatePass")
gateUnknown = Term("rkaf:gateUnknown")
generatedBy = Term("rkaf:generatedBy")
generationRun = Term("rkaf:generationRun")
governanceModel = Term("rkaf:governanceModel")
hasAILineage = Term("rkaf:hasAILineage")
hasAccessScope = Term("rkaf:hasAccessScope")
hasAgendaItemIdentifier = Term("rkaf:hasAgendaItemIdentifier")
hasApplicability = Term("rkaf:hasApplicability")
hasArtifactIdentifier = Term("rkaf:hasArtifactIdentifier")
hasAuthority = Term("rkaf:hasAuthority")
hasConfidence = Term("rkaf:hasConfidence")
hasContentDigest = Term("rkaf:hasContentDigest")
hasDocket = Term("rkaf:hasDocket")
hasDocketIdentifier = Term("rkaf:hasDocketIdentifier")
hasEffectivePeriod = Term("rkaf:hasEffectivePeriod")
hasEvidenceBinding = Term("rkaf:hasEvidenceBinding")
hasExtractionProvenance = Term("rkaf:hasExtractionProvenance")
hasJustification = Term("rkaf:hasJustification")
hasPredecessor = Term("rkaf:hasPredecessor")
hasProceedingEvidenceIdentifier = Term("rkaf:hasProceedingEvidenceIdentifier")
hasProceedingIdentifier = Term("rkaf:hasProceedingIdentifier")
hasRegulatoryIdentifier = Term("rkaf:hasRegulatoryIdentifier")
hasRetentionPolicy = Term("rkaf:hasRetentionPolicy")
hasSafetyLabel = Term("rkaf:hasSafetyLabel")
hasSourceClaimant = Term("rkaf:hasSourceClaimant")
hasWarrant = Term("rkaf:hasWarrant")
hash_sha256 = Term("rkaf:hash-sha256")
high = Term("rkaf:high")
hostedByRegistry = Term("rkaf:hostedByRegistry")
humanApprover = Term("rkaf:humanApprover")
humanAsserted = Term("rkaf:humanAsserted")
humanEstimated = Term("rkaf:humanEstimated")
humanExtraction = Term("rkaf:humanExtraction")
humanRationale = Term("rkaf:humanRationale")
humanUser = Term("rkaf:humanUser")
human_estimation = Term("rkaf:human-estimation")
identifierRegistry = Term("rkaf:identifierRegistry")
implements = Term("rkaf:implements")
imported = Term("rkaf:imported")
importedRecord = Term("rkaf:importedRecord")
independenceGroup = Term("rkaf:independenceGroup")
inferred_from_warrant_class = Term("rkaf:inferred-from-warrant-class")
informational = Term("rkaf:informational")
input = Term("rkaf:input")
inputConcept = Term("rkaf:inputConcept")
inputContextHash = Term("rkaf:inputContextHash")
inputDigest = Term("rkaf:inputDigest")
isbn = Term("rkaf:isbn")
issn = Term("rkaf:issn")
jsonpath = Term("rkaf:jsonpath")
judicialVacatur = Term("rkaf:judicialVacatur")
jurisdiction = Term("rkaf:jurisdiction")
justificationBackedBy = Term("rkaf:justificationBackedBy")
justifiedByAssertion = Term("rkaf:justifiedByAssertion")
lastAccess = Term("rkaf:lastAccess")
lastModification = Term("rkaf:lastModification")
lastVerifiedAt = Term("rkaf:lastVerifiedAt")
legal = Term("rkaf:legal")
legalValue = Term("rkaf:legalValue")
legal_hold_on_trigger = Term("rkaf:legal-hold-on-trigger")
legally_privileged = Term("rkaf:legally-privileged")
level = Term("rkaf:level")
lifecycleEvent = Term("rkaf:lifecycleEvent")
lifecycleEventKind = Term("rkaf:lifecycleEventKind")
llmHint = Term("rkaf:llmHint")
localOperational = Term("rkaf:localOperational")
localOperationalUse = Term("rkaf:localOperationalUse")
low = Term("rkaf:low")
machineAdjudicationProof = Term("rkaf:machineAdjudicationProof")
managedByRegistry = Term("rkaf:managedByRegistry")
mappingAssertion = Term("rkaf:mappingAssertion")
mappingRationale = Term("rkaf:mappingRationale")
mappingState = Term("rkaf:mappingState")
mapsToWos = Term("rkaf:mapsToWos")
materialRevision = Term("rkaf:materialRevision")
maxAttestationStalenessDays = Term("rkaf:maxAttestationStalenessDays")
medium = Term("rkaf:medium")
membershipMode = Term("rkaf:membershipMode")
membershipNotEnumerated = Term("rkaf:membershipNotEnumerated")
merge = Term("rkaf:merge")
methodological = Term("rkaf:methodological")
minimumUsageEligibility = Term("rkaf:minimumUsageEligibility")
mintingAuthority = Term("rkaf:mintingAuthority")
missingAuthority = Term("rkaf:missingAuthority")
modelExtraction = Term("rkaf:modelExtraction")
modelId = Term("rkaf:modelId")
modelVersion = Term("rkaf:modelVersion")
model_inference = Term("rkaf:model-inference")
newAssertionState = Term("rkaf:newAssertionState")
newUsageEligibility = Term("rkaf:newUsageEligibility")
newWorkProductStatus = Term("rkaf:newWorkProductStatus")
noEvidenceReason = Term("rkaf:noEvidenceReason")
noRemediationReason = Term("rkaf:noRemediationReason")
notCached = Term("rkaf:notCached")
notEligible = Term("rkaf:notEligible")
noticeGenerationTime = Term("rkaf:noticeGenerationTime")
object = Term("rkaf:object")
officialSourceMetadata = Term("rkaf:officialSourceMetadata")
officialStatus = Term("rkaf:officialStatus")
officialUse = Term("rkaf:officialUse")
official_registry = Term("rkaf:official-registry")
openLabel = Term("rkaf:openLabel")
openLabelFacet = Term("rkaf:openLabelFacet")
openLabelRole = Term("rkaf:openLabelRole")
openedAt = Term("rkaf:openedAt")
operational = Term("rkaf:operational")
operationalConflict = Term("rkaf:operationalConflict")
operationallyDependsOn = Term("rkaf:operationallyDependsOn")
organization = Term("rkaf:organization")
organizationVisible = Term("rkaf:organizationVisible")
organizational = Term("rkaf:organizational")
other = Term("rkaf:other")
packetId = Term("rkaf:packetId")
page_region = Term("rkaf:page-region")
partialMembership = Term("rkaf:partialMembership")
partnerVisible = Term("rkaf:partnerVisible")
partner_defined = Term("rkaf:partner-defined")
peerReview = Term("rkaf:peerReview")
permits_all = Term("rkaf:permits-all")
permits_axiomatic = Term("rkaf:permits-axiomatic")
permits_consensus_without_citation = Term("rkaf:permits-consensus-without-citation")
permittedRole = Term("rkaf:permittedRole")
permitted_by_safety_label = Term("rkaf:permitted-by-safety-label")
personalRestricted = Term("rkaf:personalRestricted")
precedingArtifact = Term("rkaf:precedingArtifact")
precedingVersion = Term("rkaf:precedingVersion")
predecessorConceptRelease = Term("rkaf:predecessorConceptRelease")
predecessorConcepts = Term("rkaf:predecessorConcepts")
predicate = Term("rkaf:predicate")
predicateCatalogProof = Term("rkaf:predicateCatalogProof")
priorArtifact = Term("rkaf:priorArtifact")
proceedingAffects = Term("rkaf:proceedingAffects")
proceedingAffectsCitation = Term("rkaf:proceedingAffectsCitation")
proceedingConcluded = Term("rkaf:proceedingConcluded")
proceedingDisapproved = Term("rkaf:proceedingDisapproved")
proceedingEvidenceIdentifierScheme = Term("rkaf:proceedingEvidenceIdentifierScheme")
proceedingFinal = Term("rkaf:proceedingFinal")
proceedingIdentifierScheme = Term("rkaf:proceedingIdentifierScheme")
proceedingLongterm = Term("rkaf:proceedingLongterm")
proceedingPrerule = Term("rkaf:proceedingPrerule")
proceedingProduces = Term("rkaf:proceedingProduces")
proceedingProposed = Term("rkaf:proceedingProposed")
proceedingReinstated = Term("rkaf:proceedingReinstated")
proceedingRemanded = Term("rkaf:proceedingRemanded")
proceedingStage = Term("rkaf:proceedingStage")
proceedingStayed = Term("rkaf:proceedingStayed")
proceedingSupersedes = Term("rkaf:proceedingSupersedes")
proceedingSupplemental = Term("rkaf:proceedingSupplemental")
proceedingTerminationCause = Term("rkaf:proceedingTerminationCause")
proceedingVacated = Term("rkaf:proceedingVacated")
proceedingWithdrawn = Term("rkaf:proceedingWithdrawn")
projectsTo = Term("rkaf:projectsTo")
promotion = Term("rkaf:promotion")
promptTemplateRef = Term("rkaf:promptTemplateRef")
proofComparisonContext = Term("rkaf:proofComparisonContext")
proofEvaluatedAt = Term("rkaf:proofEvaluatedAt")
proofInput = Term("rkaf:proofInput")
proofInputDigest = Term("rkaf:proofInputDigest")
proofIssuer = Term("rkaf:proofIssuer")
proofOutcome = Term("rkaf:proofOutcome")
proofPolicy = Term("rkaf:proofPolicy")
proofPolicyVersion = Term("rkaf:proofPolicyVersion")
proofRationale = Term("rkaf:proofRationale")
proofRecordDigest = Term("rkaf:proofRecordDigest")
proofResolver = Term("rkaf:proofResolver")
proofResolverVersion = Term("rkaf:proofResolverVersion")
proofSnapshot = Term("rkaf:proofSnapshot")
proofSupportingRecord = Term("rkaf:proofSupportingRecord")
proofType = Term("rkaf:proofType")
proposed = Term("rkaf:proposed")
proposedBy = Term("rkaf:proposedBy")
proposedForOperational = Term("rkaf:proposedForOperational")
proposedFromLocalConcept = Term("rkaf:proposedFromLocalConcept")
proposedUsageEligibility = Term("rkaf:proposedUsageEligibility")
provenanceClass = Term("rkaf:provenanceClass")
providesContext = Term("rkaf:providesContext")
public = Term("rkaf:public")
publication = Term("rkaf:publication")
publicationAllowed = Term("rkaf:publicationAllowed")
publicationBlocking = Term("rkaf:publicationBlocking")
publicationStatus = Term("rkaf:publicationStatus")
publicationTime = Term("rkaf:publicationTime")
published = Term("rkaf:published")
publishedInDocket = Term("rkaf:publishedInDocket")
publishedInProceeding = Term("rkaf:publishedInProceeding")
published_fragment = Term("rkaf:published-fragment")
publisher = Term("rkaf:publisher")
publisherAssigned = Term("rkaf:publisherAssigned")
qualifies = Term("rkaf:qualifies")
queuedFor = Term("rkaf:queuedFor")
rationale = Term("rkaf:rationale")
realizedByArtifact = Term("rkaf:realizedByArtifact")
referenceReleaseDigest = Term("rkaf:referenceReleaseDigest")
registeredAt = Term("rkaf:registeredAt")
registeredConcept = Term("rkaf:registeredConcept")
registeredVia = Term("rkaf:registeredVia")
registrationAuthority = Term("rkaf:registrationAuthority")
registrationEvent = Term("rkaf:registrationEvent")
registry = Term("rkaf:registry")
registryPublication = Term("rkaf:registryPublication")
registryUnavailable = Term("rkaf:registryUnavailable")
registryVersionOutOfRange = Term("rkaf:registryVersionOutOfRange")
regulatory = Term("rkaf:regulatory")
regulatoryClass = Term("rkaf:regulatoryClass")
regulatoryIdentifierScheme = Term("rkaf:regulatoryIdentifierScheme")
regulatoryRestricted = Term("rkaf:regulatoryRestricted")
rejected = Term("rkaf:rejected")
relatedConcept = Term("rkaf:relatedConcept")
relatedPublishedArtifact = Term("rkaf:relatedPublishedArtifact")
relationAdoption = Term("rkaf:relationAdoption")
relationChangeOperation = Term("rkaf:relationChangeOperation")
relationChangeStage = Term("rkaf:relationChangeStage")
relationChangeTime = Term("rkaf:relationChangeTime")
relationFindingKind = Term("rkaf:relationFindingKind")
relationRemoval = Term("rkaf:relationRemoval")
relationReplacement = Term("rkaf:relationReplacement")
relationSuspension = Term("rkaf:relationSuspension")
remediationAction = Term("rkaf:remediationAction")
replacedBy = Term("rkaf:replacedBy")
replacement = Term("rkaf:replacement")
replacementRelationObject = Term("rkaf:replacementRelationObject")
replication = Term("rkaf:replication")
requestContractDigest = Term("rkaf:requestContractDigest")
requiredAdoptionScope = Term("rkaf:requiredAdoptionScope")
requiredPredicate = Term("rkaf:requiredPredicate")
requiresEvidenceType = Term("rkaf:requiresEvidenceType")
requiresSpecExtension = Term("rkaf:requiresSpecExtension")
rescission = Term("rkaf:rescission")
rescissionEffectiveDate = Term("rkaf:rescissionEffectiveDate")
rescissionEvidence = Term("rkaf:rescissionEvidence")
resolutionEndpoint = Term("rkaf:resolutionEndpoint")
resolutionMethod = Term("rkaf:resolutionMethod")
resolutionStatus = Term("rkaf:resolutionStatus")
resolutionTrustedVia = Term("rkaf:resolutionTrustedVia")
resolved = Term("rkaf:resolved")
resolvedAt = Term("rkaf:resolvedAt")
resolvedConcept = Term("rkaf:resolvedConcept")
resolvedToConcepts = Term("rkaf:resolvedToConcepts")
resolverId = Term("rkaf:resolverId")
resourceFamily = Term("rkaf:resourceFamily")
resourceKind = Term("rkaf:resourceKind")
resourceLineage = Term("rkaf:resourceLineage")
result = Term("rkaf:result")
retainedForPointInTime = Term("rkaf:retainedForPointInTime")
retainsAssertion = Term("rkaf:retainsAssertion")
retainsWorkProduct = Term("rkaf:retainsWorkProduct")
retentionDurationDays = Term("rkaf:retentionDurationDays")
retentionPostExpiry = Term("rkaf:retentionPostExpiry")
retentionTrigger = Term("rkaf:retentionTrigger")
retired = Term("rkaf:retired")
retrievalSignal = Term("rkaf:retrievalSignal")
retroactiveFrom = Term("rkaf:retroactiveFrom")
revalidated = Term("rkaf:revalidated")
revalidation = Term("rkaf:revalidation")
revalidationClosure = Term("rkaf:revalidationClosure")
revalidationFor = Term("rkaf:revalidationFor")
revalidationOf = Term("rkaf:revalidationOf")
reviewQueueOnly = Term("rkaf:reviewQueueOnly")
reviewStatus = Term("rkaf:reviewStatus")
review_consensus = Term("rkaf:review-consensus")
reviewedAuthorityChain = Term("rkaf:reviewedAuthorityChain")
revisedUsageEligibility = Term("rkaf:revisedUsageEligibility")
revoked = Term("rkaf:revoked")
revokedAt = Term("rkaf:revokedAt")
role = Term("rkaf:role")
roleRestricted = Term("rkaf:roleRestricted")
ruleBasedExtraction = Term("rkaf:ruleBasedExtraction")
rule_based = Term("rkaf:rule-based")
safeAutomaticMigration = Term("rkaf:safeAutomaticMigration")
schemeFacet = Term("rkaf:schemeFacet")
scientific = Term("rkaf:scientific")
scope = Term("rkaf:scope")
scopeComparisonProof = Term("rkaf:scopeComparisonProof")
scopeDisjoint = Term("rkaf:scopeDisjoint")
scopeEquivalent = Term("rkaf:scopeEquivalent")
scopeObservedNarrowsExpected = Term("rkaf:scopeObservedNarrowsExpected")
scopeObservedSubsumesExpected = Term("rkaf:scopeObservedSubsumesExpected")
scopeOverlaps = Term("rkaf:scopeOverlaps")
scopeUnknown = Term("rkaf:scopeUnknown")
scopedToWorkspace = Term("rkaf:scopedToWorkspace")
score = Term("rkaf:score")
scoreCategorical = Term("rkaf:scoreCategorical")
sealedRequestDigest = Term("rkaf:sealedRequestDigest")
sealedResponseArtifact = Term("rkaf:sealedResponseArtifact")
searchOnly = Term("rkaf:searchOnly")
seed = Term("rkaf:seed")
selectorKind = Term("rkaf:selectorKind")
severity = Term("rkaf:severity")
sharedArtifact = Term("rkaf:sharedArtifact")
social = Term("rkaf:social")
sourceArtifactDigest = Term("rkaf:sourceArtifactDigest")
sourceAuthorityHint = Term("rkaf:sourceAuthorityHint")
sourceConceptRelease = Term("rkaf:sourceConceptRelease")
sourceExplicit = Term("rkaf:sourceExplicit")
sourceReliability = Term("rkaf:sourceReliability")
source_class = Term("rkaf:source-class")
source_class_inheritance = Term("rkaf:source-class-inheritance")
split = Term("rkaf:split")
splitInto = Term("rkaf:splitInto")
stale = Term("rkaf:stale")
staleCacheFallback = Term("rkaf:staleCacheFallback")
staleCacheServed = Term("rkaf:staleCacheServed")
staleConceptCache = Term("rkaf:staleConceptCache")
staleDep = Term("rkaf:staleDep")
staleDependencies = Term("rkaf:staleDependencies")
staleDependency = Term("rkaf:staleDependency")
staleForCurrentUse = Term("rkaf:staleForCurrentUse")
statisticalInference = Term("rkaf:statisticalInference")
status = Term("rkaf:status")
statutory = Term("rkaf:statutory")
structuralEvidence = Term("rkaf:structuralEvidence")
subject = Term("rkaf:subject")
subjectArtifact = Term("rkaf:subjectArtifact")
subjectAssertion = Term("rkaf:subjectAssertion")
subjectConcept = Term("rkaf:subjectConcept")
successorAssertion = Term("rkaf:successorAssertion")
successorAssertions = Term("rkaf:successorAssertions")
successorConceptRelease = Term("rkaf:successorConceptRelease")
successorConcepts = Term("rkaf:successorConcepts")
successorWorkProduct = Term("rkaf:successorWorkProduct")
suggestedRemediation = Term("rkaf:suggestedRemediation")
sunsetAt = Term("rkaf:sunsetAt")
supersededBySuccessor = Term("rkaf:supersededBySuccessor")
supersedesAssertion = Term("rkaf:supersedesAssertion")
supersedesWorkProduct = Term("rkaf:supersedesWorkProduct")
supersession = Term("rkaf:supersession")
supportedAuthorityKinds = Term("rkaf:supportedAuthorityKinds")
supportedAutomaticMigrations = Term("rkaf:supportedAutomaticMigrations")
supportedEvaluationAnchors = Term("rkaf:supportedEvaluationAnchors")
supportingEvent = Term("rkaf:supportingEvent")
supports = Term("rkaf:supports")
supportsRegistryVersionRange = Term("rkaf:supportsRegistryVersionRange")
targetAdoption = Term("rkaf:targetAdoption")
targetAssertion = Term("rkaf:targetAssertion")
targetBridgeValidation = Term("rkaf:targetBridgeValidation")
targetConceptRelease = Term("rkaf:targetConceptRelease")
targetFinding = Term("rkaf:targetFinding")
targetMappingConflict = Term("rkaf:targetMappingConflict")
targetPacket = Term("rkaf:targetPacket")
targetRegistry = Term("rkaf:targetRegistry")
targetWorkProduct = Term("rkaf:targetWorkProduct")
targets = Term("rkaf:targets")
team = Term("rkaf:team")
temperature = Term("rkaf:temperature")
textualEvidence = Term("rkaf:textualEvidence")
toConcept = Term("rkaf:toConcept")
transitionTo = Term("rkaf:transitionTo")
triggeredBy = Term("rkaf:triggeredBy")
triggeredByPacket = Term("rkaf:triggeredByPacket")
trustedRegistries = Term("rkaf:trustedRegistries")
uncalibrated = Term("rkaf:uncalibrated")
unicode_codepoint = Term("rkaf:unicode-codepoint")
unmappedButApproved = Term("rkaf:unmappedButApproved")
unresolved = Term("rkaf:unresolved")
unresolvedConcept = Term("rkaf:unresolvedConcept")
unresolvedConcepts = Term("rkaf:unresolvedConcepts")
unsupportedAnchor = Term("rkaf:unsupportedAnchor")
unsupportedAuthorityKind = Term("rkaf:unsupportedAuthorityKind")
urn_persistent = Term("rkaf:urn-persistent")
us_cfr = Term("rkaf:us-cfr")
us_eo = Term("rkaf:us-eo")
us_frdoc = Term("rkaf:us-frdoc")
us_frdoc_legacy = Term("rkaf:us-frdoc-legacy")
us_frdoc_x = Term("rkaf:us-frdoc-x")
us_pl = Term("rkaf:us-pl")
us_regsgov = Term("rkaf:us-regsgov")
us_rin = Term("rkaf:us-rin")
us_usc = Term("rkaf:us-usc")
usageCeiling = Term("rkaf:usageCeiling")
usageEligibility = Term("rkaf:usageEligibility")
usedAsAuthority = Term("rkaf:usedAsAuthority")
userAssertion = Term("rkaf:userAssertion")
uslm = Term("rkaf:uslm")
uslm_section = Term("rkaf:uslm-section")
utf16_code_unit = Term("rkaf:utf16-code-unit")
utf8_byte = Term("rkaf:utf8-byte")
valid = Term("rkaf:valid")
validForPointInTimeOnly = Term("rkaf:validForPointInTimeOnly")
validatedAt = Term("rkaf:validatedAt")
verdictNearSame = Term("rkaf:verdictNearSame")
verdictRelated = Term("rkaf:verdictRelated")
verdictSame = Term("rkaf:verdictSame")
verdictTargetBroader = Term("rkaf:verdictTargetBroader")
verdictTargetNarrower = Term("rkaf:verdictTargetNarrower")
verifiedBy = Term("rkaf:verifiedBy")
versionBasis = Term("rkaf:versionBasis")
versionLineageEvidence = Term("rkaf:versionLineageEvidence")
very_high = Term("rkaf:very-high")
very_low = Term("rkaf:very-low")
visibility = Term("rkaf:visibility")
warning = Term("rkaf:warning")
warningCode = Term("rkaf:warningCode")
warrantFamily = Term("rkaf:warrantFamily")
warrantKind = Term("rkaf:warrantKind")
withdrawal = Term("rkaf:withdrawal")
withdrawn = Term("rkaf:withdrawn")
workflowStartTime = Term("rkaf:workflowStartTime")
workflowStepStartTime = Term("rkaf:workflowStepStartTime")
workspaceId = Term("rkaf:workspaceId")
workspaceTrustList = Term("rkaf:workspaceTrustList")
xml_node_path = Term("rkaf:xml-node-path")

_TERM_NAMES: tuple[str, ...] = (
    "A3Advisory",
    "A3AdvisoryAggregated",
    "A3AuthorityCritical",
    "AILineage",
    "AccessScope",
    "AccessScopeKind",
    "AgendaItemIdentifierScheme",
    "AgendaPriority",
    "AgendaProceedingRelationship",
    "AgendaScopeStatus",
    "AgendaStage",
    "ApplicabilityScope",
    "Artifact",
    "ArtifactIdentifierScheme",
    "Assertion",
    "AssertionOrigin",
    "AssertionPolarity",
    "Attestation",
    "Authority",
    "AuthorityKindSubstitution",
    "BehaviorTestCase",
    "BridgeConsumerRegistration",
    "BridgeContractRule",
    "BridgeIssueAttestationContract",
    "BridgeValidationResult",
    "CJIS",
    "CalibrationStatus",
    "CascadeClosureV1",
    "ClaimantAttribution",
    "ClosureClaim",
    "ClosureClaimStatus",
    "CommentPeriod",
    "Concept",
    "ConceptAssignment",
    "ConceptAssignmentPredicate",
    "ConceptLifecycleOperation",
    "ConceptMapping",
    "ConceptMintingAuthority",
    "ConceptRegistry",
    "ConceptResolutionCacheStatus",
    "ConceptResolutionMethod",
    "ConceptResolutionResult",
    "ConceptResolutionStatus",
    "ConceptResolutionWithConflict",
    "ConceptScheme",
    "ConceptUsedAsAuthority",
    "ConfidenceMethod",
    "ConfidenceRecord",
    "ConsumerEffectiveDeclaration",
    "ConsumerLifecycleState",
    "ContractInternal",
    "CoordinateSystem",
    "D0DisplayOnly",
    "Docket",
    "DocketIdentifierScheme",
    "EffectivePeriod",
    "EpistemicBasis",
    "EvaluationAnchor",
    "EvidenceBinding",
    "EvidenceRole",
    "EvidentiaryFunction",
    "ExtractionActivity",
    "ExtractionMethod",
    "FERPA",
    "Finding",
    "FragmentIdentityScheme",
    "GDPR_PII",
    "GateStatus",
    "GeneratedWorkProduct",
    "HIPAA_PHI",
    "Justification",
    "LLMHint",
    "LifecycleEvent",
    "LocalAdoption",
    "LocalConcept",
    "MachineAdjudicationProof",
    "MachineAdjudicationVerdict",
    "MalformedTestCase",
    "MappingApplicabilityContext",
    "MappingState",
    "MissingJustificationMetadata",
    "MissingNode",
    "MissingStaleTransition",
    "NoEvidenceReason",
    "OutputMismatch",
    "Overlay",
    "P4Production",
    "ParseError",
    "PointInTimeException",
    "Proceeding",
    "ProceedingIdentifierScheme",
    "ProceedingStage",
    "ProceedingTerminationCause",
    "R2Review",
    "ReferenceResourceMembershipMode",
    "ReferenceResourceRelease",
    "ReferenceResourceVersionBasis",
    "RegisteredConcept",
    "RegistryConflict",
    "RegulatoryAgendaItem",
    "RegulatoryAgendaObservation",
    "RelationChangeEvent",
    "RelationChangeOperation",
    "RelationChangeStage",
    "RelationComparisonContext",
    "RelationComparisonOutcome",
    "RelationFinding",
    "RelationFindingKind",
    "RelationshipAssertion",
    "ResolverProofIssuer",
    "ResolverProofRecord",
    "ResolverProofType",
    "RetentionPolicy",
    "RevalidationClosureEvent",
    "RevalidationEvent",
    "S1Suggestion",
    "ScopeRelation",
    "SelectorKind",
    "SemverError",
    "SkosMappingPredicate",
    "SourceClaimant",
    "SourceFragment",
    "USRegulatoryIdentifierScheme",
    "UnattestedConsumerIssue",
    "UnauthorizedBroadening",
    "UnauthorizedLegalInference",
    "UnsupportedContract",
    "UnsupportedContractVersion",
    "UnsupportedEvaluationAnchor",
    "UnterminatedJustificationChain",
    "UsageEligibility",
    "UsageEligibilityReducer",
    "ValueAssertion",
    "ValueDatatype",
    "VocabularyText",
    "Warrant",
    "WarrantFamily",
    "WarrantKind",
    "Workspace",
    "absorbedConcepts",
    "abstained",
    "accepted",
    "acceptedDocumentTypes",
    "acceptedWithWarnings",
    "accessScopeKind",
    "active",
    "adjudicationVerdict",
    "administrativeConclusion",
    "adoptedAt",
    "adoptionAuthorityKind",
    "adoptionScope",
    "adoptionStatus",
    "adoptsApplicability",
    "advisory",
    "affectedAdoption",
    "affectedAdoptions",
    "affectedAssertions",
    "affectedAuthorityAssertions",
    "affectedConcepts",
    "affectedFragments",
    "affectedImplementationAssertions",
    "affectedWorkProduct",
    "affectedWorkProducts",
    "affirmed",
    "affirmedDeniedDiscrepancy",
    "agencyWithdrawal",
    "agendaAffectsCitation",
    "agendaAuthorityCitation",
    "agendaCompleted",
    "agendaFinal",
    "agendaItemIdentifierScheme",
    "agendaLongterm",
    "agendaPrerule",
    "agendaPriority",
    "agendaPriorityEconomicallySignificant",
    "agendaPriorityInfoAdminOther",
    "agendaPriorityOtherSignificant",
    "agendaPriorityRoutineFrequent",
    "agendaPrioritySubstantiveNonsignificant",
    "agendaProposed",
    "agendaScopeRecurring",
    "agendaScopeSingleObserved",
    "agendaScopeStatus",
    "agendaScopeUnresolved",
    "agendaStage",
    "agendaTracksProceeding",
    "aiAgent",
    "aiModel",
    "aiSuggested",
    "aknt_eId",
    "ambiguous",
    "amendment",
    "anchorType",
    "anchoredBy",
    "anonymize",
    "applicabilityCondition",
    "applicationDomain",
    "applicationSubmissionTime",
    "appliesInJurisdiction",
    "appliesTo",
    "appliesToSubject",
    "approved",
    "approvedWithConditions",
    "archive",
    "artifactId",
    "artifactIdentifierScheme",
    "artifactPairingProof",
    "assertedAt",
    "assertedBy",
    "asserted_by",
    "assertion",
    "assertionOrigin",
    "assertionPolarity",
    "assertionStateProof",
    "assertsObject",
    "assertsPredicate",
    "assertsSubject",
    "assertsValue",
    "assignedConceptRelease",
    "assignmentContextual",
    "assignmentMention",
    "assignmentPrimary",
    "assignmentSubstantive",
    "associatedWorkflowStep",
    "attestationScope",
    "attestedAt",
    "attestedIssueKinds",
    "attestor",
    "attestorKind",
    "attestorType",
    "attributedInFragment",
    "authoringOnly",
    "authorityBroken",
    "authorityChainStatus",
    "authorityChainTraversal",
    "authorityCitation",
    "authorityCritical",
    "authorityKind",
    "authorizedBy",
    "automatedParser",
    "axiomatic",
    "basedOnAttestation",
    "basedOnAttestations",
    "basedOnClassification",
    "basedOnEvent",
    "basedOnEvidence",
    "baselineWarrantProof",
    "behaviorContract",
    "bindsAssertion",
    "bindsSourceFragment",
    "bridgeContractVersion",
    "broadOrNarrowMatchDiscoveryOnly",
    "broken",
    "brokenAuthority",
    "brokenForNewCases",
    "cacheServed",
    "cacheStatus",
    "cachedAt",
    "calibratedAgainst",
    "calibrationStatus",
    "capabilityCap",
    "capturedAt",
    "capturedBy",
    "carrier_local_fragment",
    "cascadeAlgorithm",
    "cascadeAsOf",
    "cascadeSeed",
    "chainTerminus",
    "chainTerminusKind",
    "changeDecided",
    "changeEffective",
    "changeEvidence",
    "changeIntendedEffectiveTime",
    "changeObject",
    "changePredicate",
    "changeProposed",
    "changeStageUnclear",
    "changeSubject",
    "changeWithdrawn",
    "cid",
    "claimantAttribution",
    "claimantIdentity",
    "claimantImpliedBySource",
    "claimantIsDocumentIssuer",
    "claimantNamedInSource",
    "claimantNotStated",
    "claimantText",
    "claimsAssertion",
    "classification",
    "classified",
    "classifiedBy",
    "closeMatchAwaitingAdoption",
    "closeMatchLocallyAdopted",
    "closedAt",
    "closedBy",
    "closesRevalidation",
    "closesRevalidationEvent",
    "closureArtifact",
    "closureClaimDisabled",
    "closureClaimStatus",
    "closureDecision",
    "closureMemberDigest",
    "closurePredicateFamily",
    "closureProfileVersion",
    "closureRegion",
    "closureReviewedAt",
    "collectsEvidenceType",
    "commentPeriodDocket",
    "commentPeriodEnd",
    "commentPeriodFor",
    "commentPeriodOpenedBy",
    "commentPeriodStart",
    "commitment",
    "community",
    "communityEndorsement",
    "comparisonAffirmedDeniedDiscrepancy",
    "comparisonBaselineArtifact",
    "comparisonConflict",
    "comparisonConsumer",
    "comparisonDetector",
    "comparisonDetectorVersion",
    "comparisonEvaluationTime",
    "comparisonExpectedAssertion",
    "comparisonNotComparable",
    "comparisonObservedArtifact",
    "comparisonOutcome",
    "comparisonPolicyVersion",
    "comparisonProofRecord",
    "comparisonSatisfied",
    "comparisonScope",
    "comparisonSnapshot",
    "comparisonUnknown",
    "completeMembership",
    "concept",
    "conceptConflict",
    "conceptLifecycle",
    "conceptLifecycleOperation",
    "conceptMintingAuthority",
    "conceptResolutionResults",
    "conceptScope",
    "confidenceBasis",
    "confidenceMethod",
    "conflicting",
    "conflictingEntries",
    "conflictingMappings",
    "conflictingScope",
    "congressionalDisapproval",
    "consensus",
    "consensus_without_citation",
    "consumer",
    "consumerLifecycleState",
    "contentDerived",
    "contractRuleNumber",
    "contractVersion",
    "contractual",
    "contradicts",
    "coordinateSystem",
    "correction",
    "creation",
    "cryptographic",
    "currentTime",
    "dataConcept",
    "decision",
    "declaredAt",
    "declaredEffective",
    "declaredScope",
    "declared_hypothesis",
    "defeasible",
    "definedInScope",
    "definesScope",
    "delegated",
    "delegatedTo",
    "delegatingAuthority",
    "delete",
    "demotion",
    "denied",
    "deprecatedAt",
    "deprecation",
    "derivedFromFragment",
    "derivesAuthorityFrom",
    "detectedAt",
    "detectedBy",
    "detectedIssues",
    "deterministicDerivation",
    "deterministicExtraction",
    "deterministicParse",
    "directRegistry",
    "docketIdentifierScheme",
    "doi",
    "doi_fragment",
    "draft",
    "draftGenerationAllowed",
    "editorial",
    "editorialAssertion",
    "editorialRevision",
    "effectiveDate",
    "effectivePeriodEnd",
    "effectivePeriodStart",
    "effectiveUsageEligibility",
    "effectiveUsageEligibilityRationale",
    "eli",
    "eli_dl",
    "eli_fragment",
    "eli_i",
    "eligibilityDeterminationTime",
    "embargoUntil",
    "emittedBy",
    "empirical",
    "endorsedForReview",
    "epistemicBasis",
    "error",
    "errorCode",
    "evaluatedAgainst",
    "evaluationAnchor",
    "evaluationConsumer",
    "evaluationScopes",
    "evaluationTime",
    "eventOccurrenceTime",
    "evidenceBindingProof",
    "evidencePurpose",
    "evidenceRole",
    "evidentiaryFunction",
    "exactMatchTrusted",
    "exceptionEffectivePeriodEnd",
    "exceptionEffectivePeriodStart",
    "exceptionScope",
    "excludesCategory",
    "excludesPurposes",
    "expectedOutput",
    "expectedRuntimeError",
    "expertOpinion",
    "expired",
    "extractedBy",
    "extractionAttempt",
    "extractionMethod",
    "extractionModelRef",
    "extractionPromptRef",
    "extractionRun",
    "extractorVersion",
    "factCheck",
    "findingComparedAssertion",
    "findingComparisonContext",
    "findingDetectedAt",
    "findingFingerprint",
    "findingKind",
    "findingProofRecord",
    "findingRationale",
    "findings",
    "flaggedForReview",
    "forAssertion",
    "formalAdoptionEvent",
    "formalReviewer",
    "formspec_need",
    "fragmentContentDigest",
    "fragmentIdentityScheme",
    "fragmentType",
    "fresh",
    "fromConcept",
    "gateFail",
    "gatePass",
    "gateUnknown",
    "generatedBy",
    "generationRun",
    "governanceModel",
    "hasAILineage",
    "hasAccessScope",
    "hasAgendaItemIdentifier",
    "hasApplicability",
    "hasArtifactIdentifier",
    "hasAuthority",
    "hasConfidence",
    "hasContentDigest",
    "hasDocket",
    "hasDocketIdentifier",
    "hasEffectivePeriod",
    "hasEvidenceBinding",
    "hasExtractionProvenance",
    "hasJustification",
    "hasPredecessor",
    "hasProceedingEvidenceIdentifier",
    "hasProceedingIdentifier",
    "hasRegulatoryIdentifier",
    "hasRetentionPolicy",
    "hasSafetyLabel",
    "hasSourceClaimant",
    "hasWarrant",
    "hash_sha256",
    "high",
    "hostedByRegistry",
    "humanApprover",
    "humanAsserted",
    "humanEstimated",
    "humanExtraction",
    "humanRationale",
    "humanUser",
    "human_estimation",
    "identifierRegistry",
    "implements",
    "imported",
    "importedRecord",
    "independenceGroup",
    "inferred_from_warrant_class",
    "informational",
    "input",
    "inputConcept",
    "inputContextHash",
    "inputDigest",
    "isbn",
    "issn",
    "jsonpath",
    "judicialVacatur",
    "jurisdiction",
    "justificationBackedBy",
    "justifiedByAssertion",
    "lastAccess",
    "lastModification",
    "lastVerifiedAt",
    "legal",
    "legalValue",
    "legal_hold_on_trigger",
    "legally_privileged",
    "level",
    "lifecycleEvent",
    "lifecycleEventKind",
    "llmHint",
    "localOperational",
    "localOperationalUse",
    "low",
    "machineAdjudicationProof",
    "managedByRegistry",
    "mappingAssertion",
    "mappingRationale",
    "mappingState",
    "mapsToWos",
    "materialRevision",
    "maxAttestationStalenessDays",
    "medium",
    "membershipMode",
    "membershipNotEnumerated",
    "merge",
    "methodological",
    "minimumUsageEligibility",
    "mintingAuthority",
    "missingAuthority",
    "modelExtraction",
    "modelId",
    "modelVersion",
    "model_inference",
    "newAssertionState",
    "newUsageEligibility",
    "newWorkProductStatus",
    "noEvidenceReason",
    "noRemediationReason",
    "notCached",
    "notEligible",
    "noticeGenerationTime",
    "object",
    "officialSourceMetadata",
    "officialStatus",
    "officialUse",
    "official_registry",
    "openLabel",
    "openLabelFacet",
    "openLabelRole",
    "openedAt",
    "operational",
    "operationalConflict",
    "operationallyDependsOn",
    "organization",
    "organizationVisible",
    "organizational",
    "other",
    "packetId",
    "page_region",
    "partialMembership",
    "partnerVisible",
    "partner_defined",
    "peerReview",
    "permits_all",
    "permits_axiomatic",
    "permits_consensus_without_citation",
    "permittedRole",
    "permitted_by_safety_label",
    "personalRestricted",
    "precedingArtifact",
    "precedingVersion",
    "predecessorConceptRelease",
    "predecessorConcepts",
    "predicate",
    "predicateCatalogProof",
    "priorArtifact",
    "proceedingAffects",
    "proceedingAffectsCitation",
    "proceedingConcluded",
    "proceedingDisapproved",
    "proceedingEvidenceIdentifierScheme",
    "proceedingFinal",
    "proceedingIdentifierScheme",
    "proceedingLongterm",
    "proceedingPrerule",
    "proceedingProduces",
    "proceedingProposed",
    "proceedingReinstated",
    "proceedingRemanded",
    "proceedingStage",
    "proceedingStayed",
    "proceedingSupersedes",
    "proceedingSupplemental",
    "proceedingTerminationCause",
    "proceedingVacated",
    "proceedingWithdrawn",
    "projectsTo",
    "promotion",
    "promptTemplateRef",
    "proofComparisonContext",
    "proofEvaluatedAt",
    "proofInput",
    "proofInputDigest",
    "proofIssuer",
    "proofOutcome",
    "proofPolicy",
    "proofPolicyVersion",
    "proofRationale",
    "proofRecordDigest",
    "proofResolver",
    "proofResolverVersion",
    "proofSnapshot",
    "proofSupportingRecord",
    "proofType",
    "proposed",
    "proposedBy",
    "proposedForOperational",
    "proposedFromLocalConcept",
    "proposedUsageEligibility",
    "provenanceClass",
    "providesContext",
    "public",
    "publication",
    "publicationAllowed",
    "publicationBlocking",
    "publicationStatus",
    "publicationTime",
    "published",
    "publishedInDocket",
    "publishedInProceeding",
    "published_fragment",
    "publisher",
    "publisherAssigned",
    "qualifies",
    "queuedFor",
    "rationale",
    "realizedByArtifact",
    "referenceReleaseDigest",
    "registeredAt",
    "registeredConcept",
    "registeredVia",
    "registrationAuthority",
    "registrationEvent",
    "registry",
    "registryPublication",
    "registryUnavailable",
    "registryVersionOutOfRange",
    "regulatory",
    "regulatoryClass",
    "regulatoryIdentifierScheme",
    "regulatoryRestricted",
    "rejected",
    "relatedConcept",
    "relatedPublishedArtifact",
    "relationAdoption",
    "relationChangeOperation",
    "relationChangeStage",
    "relationChangeTime",
    "relationFindingKind",
    "relationRemoval",
    "relationReplacement",
    "relationSuspension",
    "remediationAction",
    "replacedBy",
    "replacement",
    "replacementRelationObject",
    "replication",
    "requestContractDigest",
    "requiredAdoptionScope",
    "requiredPredicate",
    "requiresEvidenceType",
    "requiresSpecExtension",
    "rescission",
    "rescissionEffectiveDate",
    "rescissionEvidence",
    "resolutionEndpoint",
    "resolutionMethod",
    "resolutionStatus",
    "resolutionTrustedVia",
    "resolved",
    "resolvedAt",
    "resolvedConcept",
    "resolvedToConcepts",
    "resolverId",
    "resourceFamily",
    "resourceKind",
    "resourceLineage",
    "result",
    "retainedForPointInTime",
    "retainsAssertion",
    "retainsWorkProduct",
    "retentionDurationDays",
    "retentionPostExpiry",
    "retentionTrigger",
    "retired",
    "retrievalSignal",
    "retroactiveFrom",
    "revalidated",
    "revalidation",
    "revalidationClosure",
    "revalidationFor",
    "revalidationOf",
    "reviewQueueOnly",
    "reviewStatus",
    "review_consensus",
    "reviewedAuthorityChain",
    "revisedUsageEligibility",
    "revoked",
    "revokedAt",
    "role",
    "roleRestricted",
    "ruleBasedExtraction",
    "rule_based",
    "safeAutomaticMigration",
    "schemeFacet",
    "scientific",
    "scope",
    "scopeComparisonProof",
    "scopeDisjoint",
    "scopeEquivalent",
    "scopeObservedNarrowsExpected",
    "scopeObservedSubsumesExpected",
    "scopeOverlaps",
    "scopeUnknown",
    "scopedToWorkspace",
    "score",
    "scoreCategorical",
    "sealedRequestDigest",
    "sealedResponseArtifact",
    "searchOnly",
    "seed",
    "selectorKind",
    "severity",
    "sharedArtifact",
    "social",
    "sourceArtifactDigest",
    "sourceAuthorityHint",
    "sourceConceptRelease",
    "sourceExplicit",
    "sourceReliability",
    "source_class",
    "source_class_inheritance",
    "split",
    "splitInto",
    "stale",
    "staleCacheFallback",
    "staleCacheServed",
    "staleConceptCache",
    "staleDep",
    "staleDependencies",
    "staleDependency",
    "staleForCurrentUse",
    "statisticalInference",
    "status",
    "statutory",
    "structuralEvidence",
    "subject",
    "subjectArtifact",
    "subjectAssertion",
    "subjectConcept",
    "successorAssertion",
    "successorAssertions",
    "successorConceptRelease",
    "successorConcepts",
    "successorWorkProduct",
    "suggestedRemediation",
    "sunsetAt",
    "supersededBySuccessor",
    "supersedesAssertion",
    "supersedesWorkProduct",
    "supersession",
    "supportedAuthorityKinds",
    "supportedAutomaticMigrations",
    "supportedEvaluationAnchors",
    "supportingEvent",
    "supports",
    "supportsRegistryVersionRange",
    "targetAdoption",
    "targetAssertion",
    "targetBridgeValidation",
    "targetConceptRelease",
    "targetFinding",
    "targetMappingConflict",
    "targetPacket",
    "targetRegistry",
    "targetWorkProduct",
    "targets",
    "team",
    "temperature",
    "textualEvidence",
    "toConcept",
    "transitionTo",
    "triggeredBy",
    "triggeredByPacket",
    "trustedRegistries",
    "uncalibrated",
    "unicode_codepoint",
    "unmappedButApproved",
    "unresolved",
    "unresolvedConcept",
    "unresolvedConcepts",
    "unsupportedAnchor",
    "unsupportedAuthorityKind",
    "urn_persistent",
    "us_cfr",
    "us_eo",
    "us_frdoc",
    "us_frdoc_legacy",
    "us_frdoc_x",
    "us_pl",
    "us_regsgov",
    "us_rin",
    "us_usc",
    "usageCeiling",
    "usageEligibility",
    "usedAsAuthority",
    "userAssertion",
    "uslm",
    "uslm_section",
    "utf16_code_unit",
    "utf8_byte",
    "valid",
    "validForPointInTimeOnly",
    "validatedAt",
    "verdictNearSame",
    "verdictRelated",
    "verdictSame",
    "verdictTargetBroader",
    "verdictTargetNarrower",
    "verifiedBy",
    "versionBasis",
    "versionLineageEvidence",
    "very_high",
    "very_low",
    "visibility",
    "warning",
    "warningCode",
    "warrantFamily",
    "warrantKind",
    "withdrawal",
    "withdrawn",
    "workflowStartTime",
    "workflowStepStartTime",
    "workspaceId",
    "workspaceTrustList",
    "xml_node_path",
)

#: Every declared term as its compact IRI. Derived from the attributes
#: above, so the set and the module cannot disagree.
TERMS: frozenset[Term] = frozenset(globals()[_name] for _name in _TERM_NAMES)

__all__ = ["RKAF_NAMESPACE", "TERMS", "Term", *_TERM_NAMES]


def __getattr__(name: str) -> Term:
    """Refuse any name that is not a term Rulespec declares."""
    raise AttributeError(
        f"'rkaf:{name}' is not a term this Rulespec contract declares "
        f"({len(TERMS)} terms). A term that was renamed, retired, or never "
        "minted fails here rather than reaching the wire."
    )

